/* Efectos de píxel, estilización, arte, render y textura.
   Todos pasan por runFilter: no alteran la capa de origen y conservan
   sus parámetros para poder reabrirlos desde el panel de capas. */
import { runFilter } from "./basic.js";
import { slider, pickerGroup } from "../editor/adjust.js";
import { activeLayer } from "../core/doc.js";
import { gpuConvolution5, gpuMorphology } from "../editor/webgpu.js";

const PREVIEW_PIXELS=5e5,clamp=v=>v<0?0:v>255?255:v;
function selectRow(label,value,items,change){const r=document.createElement("div"),l=document.createElement("label"),s=document.createElement("select");r.className="field";s.className="grow";l.textContent=label;for(const [v,t] of items){const o=document.createElement("option");o.value=v;o.textContent=t;o.selected=v===value;s.append(o);}s.onchange=()=>change(s.value);r.append(l,s);return r;}
function controls(items){const b=document.createElement("div");b.append(pickerGroup(items));return b;}
function proxy(src,final){const w=src.width,h=src.height;if(final||w*h<=PREVIEW_PIXELS){const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d",{willReadFrequently:true}).drawImage(src,0,0);return{c,w,h,s:1};}const s=Math.sqrt(PREVIEW_PIXELS/(w*h)),pw=Math.max(1,Math.round(w*s)),ph=Math.max(1,Math.round(h*s)),c=document.createElement("canvas");c.width=pw;c.height=ph;c.getContext("2d",{willReadFrequently:true}).drawImage(src,0,0,pw,ph);return{c,w:pw,h:ph,s};}
function image(c){return c.getContext("2d",{willReadFrequently:true}).getImageData(0,0,c.width,c.height);}
function put(layer,c,im){c.getContext("2d").putImageData(im,0,0);const x=layer.ctx;x.save();x.globalCompositeOperation="copy";x.imageSmoothingEnabled=true;x.imageSmoothingQuality="high";x.drawImage(c,0,0,layer.canvas.width,layer.canvas.height);x.restore();}
function copyCanvas(src){const c=document.createElement("canvas");c.width=src.width;c.height=src.height;c.getContext("2d").drawImage(src,0,0);return c;}
function blur(src,r){if(r<.1)return copyCanvas(src);const c=copyCanvas(src),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);x.filter=`blur(${r}px)`;x.drawImage(src,0,0);x.filter="none";return c;}
function bilinear(d,w,h,x,y,k){x=Math.max(0,Math.min(w-1,x));y=Math.max(0,Math.min(h-1,y));const x0=x|0,y0=y|0,x1=Math.min(w-1,x0+1),y1=Math.min(h-1,y0+1),fx=x-x0,fy=y-y0,a=d[(y0*w+x0)*4+k],b=d[(y0*w+x1)*4+k],c=d[(y1*w+x0)*4+k],e=d[(y1*w+x1)*4+k];return(a+(b-a)*fx)*(1-fy)+(c+(e-c)*fx)*fy;}
function hash(x,y,seed=1){let n=(x*374761393+y*668265263+seed*69069)|0;n=(n^(n>>>13))*1274126177;return((n^(n>>>16))>>>0)/4294967295;}
function lum(d,i){return .2126*d[i]+.7152*d[i+1]+.0722*d[i+2];}
function edgeMap(d,w,h,x,y){const at=(xx,yy)=>lum(d,(Math.max(0,Math.min(h-1,yy))*w+Math.max(0,Math.min(w-1,xx)))*4),gx=-at(x-1,y-1)-2*at(x-1,y)-at(x-1,y+1)+at(x+1,y-1)+2*at(x+1,y)+at(x+1,y+1),gy=-at(x-1,y-1)-2*at(x,y-1)-at(x+1,y-1)+at(x-1,y+1)+2*at(x,y+1)+at(x+1,y+1);return Math.min(255,Math.hypot(gx,gy));}

function applyPixel(layer,src,final,p){const q=proxy(src,final),im=image(q.c),d=im.data,b=Math.max(2,Math.round(p.size*q.s)),x=q.c.getContext("2d");
  if(p.mode==="fragment"){const out=new Uint8ClampedArray(d.length),off=Math.max(1,b>>1);for(let y=0;y<q.h;y++)for(let xx=0;xx<q.w;xx++){const i=(y*q.w+xx)*4;for(let k=0;k<4;k++)out[i+k]=(bilinear(d,q.w,q.h,xx-off,y,k)+bilinear(d,q.w,q.h,xx+off,y,k)+bilinear(d,q.w,q.h,xx,y-off,k)+bilinear(d,q.w,q.h,xx,y+off,k))/4;}im.data.set(out);put(layer,q.c,im);return;}
  if(p.mode==="point"||p.mode==="halftone"){const original=copyCanvas(q.c);x.fillStyle=p.mode==="halftone"?"#fff":"#181818";x.fillRect(0,0,q.w,q.h);const od=image(original).data;for(let yy=0;yy<q.h;yy+=b)for(let xx=0;xx<q.w;xx+=b){const sx=Math.min(q.w-1,xx+(b>>1)),sy=Math.min(q.h-1,yy+(b>>1)),i=(sy*q.w+sx)*4;if(p.mode==="point"){const r=b*(.18+.32*(1-lum(od,i)/255));x.fillStyle=`rgb(${od[i]},${od[i+1]},${od[i+2]})`;x.beginPath();x.arc(sx,sy,r,0,Math.PI*2);x.fill();}else{const colors=[[0,255,255,"multiply"],[255,0,255,"multiply"],[255,255,0,"multiply"],[0,0,0,"multiply"]];for(let k=0;k<4;k++){const v=k===3?1-lum(od,i)/255:1-od[i+k]/255,r=b*.42*Math.sqrt(Math.max(0,v));x.globalCompositeOperation=colors[k][3];x.fillStyle=`rgb(${colors[k][0]},${colors[k][1]},${colors[k][2]})`;x.beginPath();x.arc(sx+(k-1.5)*b*.08,sy+(k%2-.5)*b*.1,r,0,Math.PI*2);x.fill();}}}x.globalCompositeOperation="source-over";const out=image(q.c);put(layer,q.c,out);return;}
  for(let yy=0;yy<q.h;yy+=b)for(let xx=0;xx<q.w;xx+=b){let sx=xx+(b>>1),sy=yy+(b>>1);if(p.mode==="crystal"){sx=xx+hash(xx,yy,p.seed)*b;sy=yy+hash(yy,xx,p.seed+9)*b;}sx=Math.min(q.w-1,sx|0);sy=Math.min(q.h-1,sy|0);const si=(sy*q.w+sx)*4;for(let y=yy;y<Math.min(q.h,yy+b);y++)for(let z=xx;z<Math.min(q.w,xx+b);z++){const i=(y*q.w+z)*4;for(let k=0;k<3;k++)d[i+k]=d[si+k];}}
  put(layer,q.c,im);
}
export function pixelate(opts={}){const p={mode:"mosaic",size:12,seed:7,...opts.init};return runFilter({title:"Pixelizar",id:"pixelate-suite",params:p,build(preview){const b=controls([{label:"Tamaño",node:slider("Tamaño",2,80,p.size,v=>{p.size=v;preview();}," px")}]);b.prepend(selectRow("Efecto",p.mode,[["mosaic","Mosaico"],["crystal","Cristalizar"],["point","Puntillismo"],["halftone","Semitono de color"],["fragment","Fragmentar"]],v=>{p.mode=v;preview();}));return b;},apply:(l,s,f)=>applyPixel(l,s,f,p)},opts);}

function applyStylize(layer,src,final,p){const q=proxy(src,final),im=image(q.c),d=im.data,out=new Uint8ClampedArray(d),amt=p.amount/100,r=Math.max(1,Math.round(p.size*q.s));
  if(p.mode==="tiles"){const x=q.c.getContext("2d"),orig=copyCanvas(q.c),gap=Math.max(1,Math.round(r*.15));x.fillStyle=p.bg;x.fillRect(0,0,q.w,q.h);for(let y=0;y<q.h;y+=r)for(let z=0;z<q.w;z+=r){const dx=(hash(z,y,p.seed)-.5)*r*.45,dy=(hash(y,z,p.seed)-.5)*r*.45;x.drawImage(orig,z,y,Math.min(r-gap,q.w-z),Math.min(r-gap,q.h-y),z+dx,y+dy,Math.min(r-gap,q.w-z),Math.min(r-gap,q.h-y));}put(layer,q.c,image(q.c));return;}
  if(p.mode==="extrude"){const x=q.c.getContext("2d"),orig=copyCanvas(q.c);x.fillStyle=p.bg;x.fillRect(0,0,q.w,q.h);for(let y=0;y<q.h;y+=r)for(let z=0;z<q.w;z+=r){const h=(hash(z,y,p.seed)-.2)*r*amt*2;x.drawImage(orig,z,y,r,r,z+h*.55,y-h,r,r);}put(layer,q.c,image(q.c));return;}
  for(let y=0;y<q.h;y++)for(let x=0;x<q.w;x++){const i=(y*q.w+x)*4,e=edgeMap(d,q.w,q.h,x,y);if(p.mode==="glow"){for(let k=0;k<3;k++)out[i+k]=clamp((255-d[i+k])*(e/255)*2*amt);}else if(p.mode==="solar"){for(let k=0;k<3;k++){const v=d[i+k],s=v<128?v*2:(255-v)*2;out[i+k]=v+(s-v)*amt;}}else if(p.mode==="wind"){const reach=Math.round(r*(.25+hash(y,0,p.seed)));for(let k=0;k<3;k++){const v=bilinear(d,q.w,q.h,x-reach,y,k);out[i+k]=d[i+k]+(v-d[i+k])*amt*.7;}}else if(p.mode==="diffuse"){const a=hash(x,y,p.seed)*Math.PI*2,rr=r*hash(y,x,p.seed+2);for(let k=0;k<3;k++)out[i+k]=bilinear(d,q.w,q.h,x+Math.cos(a)*rr,y+Math.sin(a)*rr,k);}else if(p.mode==="oil"){const bins=12,count=new Uint16Array(bins),sum=new Uint32Array(bins*3);for(let yy=Math.max(0,y-r);yy<=Math.min(q.h-1,y+r);yy++)for(let xx=Math.max(0,x-r);xx<=Math.min(q.w-1,x+r);xx++){const j=(yy*q.w+xx)*4,b=Math.min(bins-1,(lum(d,j)*bins/256)|0);count[b]++;for(let k=0;k<3;k++)sum[b*3+k]+=d[j+k];}let best=0;for(let b=1;b<bins;b++)if(count[b]>count[best])best=b;for(let k=0;k<3;k++)out[i+k]=sum[best*3+k]/Math.max(1,count[best]);}out[i+3]=d[i+3];}im.data.set(out);put(layer,q.c,im);}
export function stylizeEffects(opts={}){const p={mode:"glow",amount:80,size:8,seed:3,bg:"#181818",...opts.init};return runFilter({title:"Efectos de estilización",id:"stylize-effects",params:p,build(preview){const b=controls([{label:"Intensidad",node:slider("Intensidad",0,100,p.amount,v=>{p.amount=v;preview();},"%")},{label:"Tamaño",node:slider("Tamaño",1,40,p.size,v=>{p.size=v;preview();}," px")}]);b.prepend(selectRow("Efecto",p.mode,[["glow","Bordes resplandecientes"],["solar","Solarizar"],["wind","Viento"],["tiles","Azulejos"],["diffuse","Difusión"],["extrude","Extrusión"],["oil","Pintura al óleo"]],v=>{p.mode=v;preview();}));return b;},apply:(l,s,f)=>applyStylize(l,s,f,p)},opts);}

function artisticCanvas(src,p,final=true){const fake={canvas:document.createElement("canvas")};fake.canvas.width=src.width;fake.canvas.height=src.height;fake.ctx=fake.canvas.getContext("2d");applyArtistic(fake,src,final,p);return fake.canvas;}
function applyArtistic(layer,src,final,p){const q=proxy(src,final),base=p.mode==="watercolor"?blur(q.c,Math.max(.5,p.size*q.s*.35)):q.c,im=image(base),d=im.data,out=new Uint8ClampedArray(d),levels=Math.max(2,Math.round(p.detail)),step=255/(levels-1),amt=p.amount/100;
  for(let y=0;y<q.h;y++)for(let x=0;x<q.w;x++){const i=(y*q.w+x)*4,e=edgeMap(d,q.w,q.h,x,y)/255,n=hash(x,y,p.seed)-.5;for(let k=0;k<3;k++){let v=d[i+k];if(p.mode==="watercolor")v=Math.round(v/step)*step-e*55*amt+n*16;else if(p.mode==="dry")v=Math.round(v/step)*step+n*75*amt+(hash(x+(y>>2),0,p.seed)>.72?-35:0);else if(p.mode==="cutout")v=Math.round(v/step)*step;else if(p.mode==="poster")v=Math.round(v/step)*step-e*130*amt;else if(p.mode==="film")v=(v-128)*(1+amt*.35)+128+n*95*amt;else if(p.mode==="pencil"){const gray=lum(d,i);v=(k===0?1:.88)*clamp(245-gray*.2-e*210*amt+n*18);}out[i+k]=clamp(d[i+k]+(v-d[i+k])*amt);}out[i+3]=d[i+3];}im.data.set(out);put(layer,base,im);}
export function artisticGallery(opts={}){const p={mode:"watercolor",amount:80,size:5,detail:6,seed:4,...opts.init};return runFilter({title:"Galería de filtros artísticos",id:"artistic-gallery",params:p,wide:true,build(preview){const root=document.createElement("div");root.className="art-gallery";const canvas=document.createElement("canvas");canvas.className="art-preview";canvas.width=520;canvas.height=320;const names=[["watercolor","Acuarela"],["dry","Pincel seco"],["cutout","Recortes"],["poster","Bordes de póster"],["film","Grano de película"],["pencil","Lápiz de color"]],choices=document.createElement("div");choices.className="art-choices";const update=()=>{const src=activeLayer()?.canvas;if(!src)return;const scale=Math.min(canvas.width/src.width,canvas.height/src.height),w=Math.max(1,Math.round(src.width*scale)),h=Math.max(1,Math.round(src.height*scale)),small=document.createElement("canvas");small.width=w;small.height=h;small.getContext("2d").drawImage(src,0,0,w,h);const out=artisticCanvas(small,p,true),x=canvas.getContext("2d");x.fillStyle="#111";x.fillRect(0,0,canvas.width,canvas.height);x.drawImage(out,(canvas.width-w)/2,(canvas.height-h)/2);for(const b of choices.children)b.classList.toggle("active",b.dataset.mode===p.mode);};for(const [mode,name] of names){const b=document.createElement("button");b.type="button";b.dataset.mode=mode;b.textContent=name;b.onclick=()=>{p.mode=mode;update();preview();};choices.append(b);}const box=controls([{label:"Intensidad",node:slider("Intensidad",0,100,p.amount,v=>{p.amount=v;update();preview();},"%")},{label:"Tamaño",node:slider("Tamaño",1,16,p.size,v=>{p.size=v;update();preview();}," px")},{label:"Detalle",node:slider("Detalle",2,12,p.detail,v=>{p.detail=v;update();preview();})}]);root.append(canvas,choices,box);requestAnimationFrame(update);return root;},apply:(l,s,f)=>applyArtistic(l,s,f,p)},opts);}

function applyRender(layer,src,final,p){const q=proxy(src,final),im=image(q.c),d=im.data,out=new Uint8ClampedArray(d),amt=p.amount/100,cx=q.w*p.x/100,cy=q.h*p.y/100,scale=Math.max(4,p.size*q.s),seed=p.seed|0;
  const valueNoise=(x,y)=>{const gx=Math.floor(x/scale),gy=Math.floor(y/scale),fx=x/scale-gx,fy=y/scale-gy,s=t=>t*t*(3-2*t),a=hash(gx,gy,seed),b=hash(gx+1,gy,seed),c=hash(gx,gy+1,seed),e=hash(gx+1,gy+1,seed);return(a+(b-a)*s(fx))*(1-s(fy))+(c+(e-c)*s(fx))*s(fy);};
  for(let y=0;y<q.h;y++)for(let x=0;x<q.w;x++){const i=(y*q.w+x)*4,dx=x-cx,dy=y-cy,dist=Math.hypot(dx,dy),n=valueNoise(x,y);for(let k=0;k<3;k++){let v=d[i+k];if(p.mode==="clouds")v=d[i+k]*(1-amt)+n*255*amt;else if(p.mode==="difference")v=Math.abs(d[i+k]-n*255*amt);else if(p.mode==="fibers"){const f=hash(x+(y>>2),y%Math.max(2,scale|0),seed)*.7+hash(x,0,seed)*.3;v=d[i+k]*(1-amt)+f*255*amt;}else if(p.mode==="flare"){const core=Math.max(0,1-dist/scale),ray=Math.max(0,Math.cos(Math.atan2(dy,dx)*8))*Math.max(0,1-dist/(scale*4))*.22,g1=Math.max(0,1-Math.abs(dist-scale*1.8)/(scale*.18))*.35,g2=Math.max(0,1-Math.hypot(x-(q.w-cx)*.55,y-(q.h-cy)*.55)/(scale*.55))*.25;const color=[255,205,125][k];v=clamp(v+(core*core+ray+g1+g2)*color*amt);}else if(p.mode==="lighting"){const cone=Math.max(0,1-dist/(scale*3)),bump=edgeMap(d,q.w,q.h,x,y)/255;v=v*(.35+.65*cone)+bump*90*amt;}else if(p.mode==="frame"){const edge=Math.min(x,y,q.w-1-x,q.h-1-y),f=edge<scale?1-edge/scale:0;v=v*(1-f*amt)+p.frameLight*(f*amt);}out[i+k]=clamp(v);}out[i+3]=d[i+3];}
  im.data.set(out);q.c.getContext("2d").putImageData(im,0,0);
  if(p.mode==="tree"){const x=q.c.getContext("2d");x.save();x.globalCompositeOperation="source-over";x.strokeStyle=`rgba(70,45,24,${amt})`;x.lineCap="round";const branch=(px,py,len,a,depth)=>{if(depth<1)return;x.lineWidth=Math.max(1,depth*q.s);const nx=px+Math.cos(a)*len,ny=py+Math.sin(a)*len;x.beginPath();x.moveTo(px,py);x.lineTo(nx,ny);x.stroke();branch(nx,ny,len*.72,a-.35-hash(depth,seed)*.22,depth-1);branch(nx,ny,len*.7,a+.35+hash(seed,depth)*.22,depth-1);};branch(q.w/2,q.h*.92,Math.min(q.w,q.h)*.2,-Math.PI/2,Math.min(9,Math.max(3,Math.round(p.detail))));x.restore();}
  put(layer,q.c,image(q.c));
}
export function renderEffects(opts={}){const p={mode:"clouds",amount:70,size:70,x:50,y:45,detail:7,seed:5,frameLight:25,...opts.init};return runFilter({title:"Interpretar",id:"render-effects",params:p,build(preview){const b=controls([{label:"Intensidad",node:slider("Intensidad",0,100,p.amount,v=>{p.amount=v;preview();},"%")},{label:"Escala",node:slider("Escala",8,240,p.size,v=>{p.size=v;preview();}," px")},{label:"Posición X",node:slider("Posición X",0,100,p.x,v=>{p.x=v;preview();},"%")},{label:"Posición Y",node:slider("Posición Y",0,100,p.y,v=>{p.y=v;preview();},"%")},{label:"Detalle",node:slider("Detalle",3,9,p.detail,v=>{p.detail=v;preview();})}]);b.prepend(selectRow("Efecto",p.mode,[["clouds","Nubes"],["difference","Nubes de diferencia"],["fibers","Fibras"],["flare","Destello de lente"],["lighting","Efectos de iluminación"],["tree","Árbol"],["frame","Marco"]],v=>{p.mode=v;preview();}));return b;},apply:(l,s,f)=>applyRender(l,s,f,p)},opts);}

function applyTexture(layer,src,final,p){const q=proxy(src,final),im=image(q.c),d=im.data,out=new Uint8ClampedArray(d),amt=p.amount/100,size=Math.max(2,Math.round(p.size*q.s));for(let y=0;y<q.h;y++)for(let x=0;x<q.w;x++){const i=(y*q.w+x)*4,n=hash(x,y,p.seed)-.5;let pattern=n;if(p.mode==="texture")pattern=(Math.sin(x/size*6.28)+Math.sin(y/size*6.28))*.25+n*.4;else if(p.mode==="tile")pattern=((x%size<2||y%size<2)?-.8:.15);else if(p.mode==="crackle"){const cell=hash(Math.floor(x/size),Math.floor(y/size),p.seed),near=Math.min(x%size,size-x%size,y%size,size-y%size);pattern=near<1+cell*2?-1:.12;}for(let k=0;k<3;k++)out[i+k]=clamp(d[i+k]+pattern*110*amt);out[i+3]=d[i+3];}im.data.set(out);put(layer,q.c,im);}
export function textureEffects(opts={}){const p={mode:"texture",amount:45,size:18,seed:8,...opts.init};return runFilter({title:"Textura y grano",id:"texture-effects",params:p,build(preview){const b=controls([{label:"Cantidad",node:slider("Cantidad",0,100,p.amount,v=>{p.amount=v;preview();},"%")},{label:"Escala",node:slider("Escala",2,100,p.size,v=>{p.size=v;preview();}," px")},{label:"Semilla",node:slider("Semilla",1,99,p.seed,v=>{p.seed=v;preview();})}]);b.prepend(selectRow("Textura",p.mode,[["texture","Texturizador"],["grain","Grano configurable"],["tile","Mosaico de azulejos"],["crackle","Craquelado"]],v=>{p.mode=v;preview();}));return b;},apply:(l,s,f)=>applyTexture(l,s,f,p)},opts);}

function kernelGrid(p,preview){const g=document.createElement("div");g.className="kernel-grid";for(let i=0;i<25;i++){const n=document.createElement("input");n.type="number";n.step=".1";n.value=p.kernel[i];n.setAttribute("aria-label",`Kernel ${Math.floor(i/5)+1}, ${i%5+1}`);n.onchange=()=>{p.kernel[i]=Number(n.value)||0;preview();};g.append(n);}return g;}
async function applyConvolution(layer,src,final,p){const q=proxy(src,final),div=Math.abs(p.divisor)>.0001?p.divisor:1,gpu=await gpuConvolution5(q.c,p.kernel,div,p.offset);if(gpu){const x=layer.ctx;x.save();x.globalCompositeOperation="copy";x.drawImage(gpu,0,0,layer.canvas.width,layer.canvas.height);x.restore();return;}const im=image(q.c),d=im.data,out=new Uint8ClampedArray(d);for(let y=0;y<q.h;y++)for(let x=0;x<q.w;x++){const i=(y*q.w+x)*4;for(let c=0;c<3;c++){let sum=0;for(let ky=-2;ky<=2;ky++)for(let kx=-2;kx<=2;kx++)sum+=bilinear(d,q.w,q.h,x+kx,y+ky,c)*p.kernel[(ky+2)*5+kx+2];out[i+c]=clamp(sum/div+p.offset);}out[i+3]=d[i+3];}im.data.set(out);put(layer,q.c,im);}
export function customConvolution(opts={}){const p={kernel:[0,0,0,0,0,0,0,-1,0,0,0,-1,5,-1,0,0,0,-1,0,0,0,0,0,0,0],divisor:1,offset:0,...opts.init};return runFilter({title:"Convolución personalizada 5×5",id:"custom-convolution",params:p,build(preview){const b=document.createElement("div");b.className="convolution-panel";b.append(kernelGrid(p,preview));b.append(controls([{label:"Divisor",node:slider("Divisor",-20,20,p.divisor,v=>{p.divisor=v;preview();},"",.1)},{label:"Desplazamiento",node:slider("Desplazamiento",-255,255,p.offset,v=>{p.offset=v;preview();})}]));return b;},apply:(l,s,f)=>applyConvolution(l,s,f,p)},opts);}

async function applyOffsetMorph(layer,src,final,p){const q=proxy(src,final),r=Math.max(1,Math.round(p.radius*q.s));if(p.mode!=="offset"){const gpu=await gpuMorphology(q.c,r,p.mode==="minimum");if(gpu){const x=layer.ctx;x.save();x.globalCompositeOperation="copy";x.drawImage(gpu,0,0,layer.canvas.width,layer.canvas.height);x.restore();return;}}const im=image(q.c),d=im.data,out=new Uint8ClampedArray(d),ox=Math.round(p.x*q.s),oy=Math.round(p.y*q.s);for(let y=0;y<q.h;y++)for(let x=0;x<q.w;x++){const i=(y*q.w+x)*4;if(p.mode==="offset"){const sx=(x-ox%q.w+q.w)%q.w,sy=(y-oy%q.h+q.h)%q.h;for(let k=0;k<4;k++)out[i+k]=d[(sy*q.w+sx)*4+k];}else{for(let k=0;k<3;k++){let v=p.mode==="minimum"?255:0;for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++){const z=bilinear(d,q.w,q.h,x+xx,y+yy,k);v=p.mode==="minimum"?Math.min(v,z):Math.max(v,z);}out[i+k]=v;}out[i+3]=d[i+3];}}im.data.set(out);put(layer,q.c,im);}
export function offsetMorphology(opts={}){const p={mode:"offset",x:100,y:100,radius:2,...opts.init};return runFilter({title:"Desplazar / mínimo / máximo",id:"offset-morphology",params:p,build(preview){const b=controls([{label:"Horizontal",node:slider("Horizontal",-1000,1000,p.x,v=>{p.x=v;preview();}," px")},{label:"Vertical",node:slider("Vertical",-1000,1000,p.y,v=>{p.y=v;preview();}," px")},{label:"Radio",node:slider("Radio",1,20,p.radius,v=>{p.radius=v;preview();}," px")}]);b.prepend(selectRow("Operación",p.mode,[["offset","Desplazamiento sin costuras"],["minimum","Mínimo · contraer claros"],["maximum","Máximo · expandir claros"]],v=>{p.mode=v;preview();}));return b;},apply:(l,s,f)=>applyOffsetMorph(l,s,f,p)},opts);}
