/* Ajustes avanzados de color y tono. Todos usan runAdjust: vista previa,
   capa independiente, reapertura, porcentaje y UI compacta móvil. */
import { doc, activeLayer } from "../core/doc.js";
import { runAdjust, slider, pickerGroup, liftImageAbove } from "./adjust.js";
import { toImage } from "./view.js";
import { curveEditor, curveLut } from "./curves.js";
import { toast } from "../ui/toast.js";
import { premiumSwitch, premiumPref } from "../ui/premium.js";
import { isMobile } from "../core/device.js";
import { applyAutoToneColorPremium, autoToneColorPlan, autoToneColorLuts } from "./tonepremium.js";
import { clamp, hueDist, rgbHsl, hslRgb, BANDS, defaultRanges, nearestBand, rangeHslBasic, rangeHslPremium } from "./rangehsl.js";

const srgb=v=>{v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4);};
const inv=v=>255*(v<=.0031308?12.92*v:1.055*Math.pow(Math.max(0,v),1/2.4)-.055);
function rgbLab(r,g,b){r=srgb(r);g=srgb(g);b=srgb(b);let x=(r*.4124+g*.3576+b*.1805)/.95047,y=(r*.2126+g*.7152+b*.0722),z=(r*.0193+g*.1192+b*.9505)/1.08883;const f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;x=f(x);y=f(y);z=f(z);return[116*y-16,500*(x-y),200*(y-z)];}
function labRgb(L,a,b){const fy=(L+16)/116,fx=fy+a/500,fz=fy-b/200,fi=t=>t**3>.008856?t**3:(t-16/116)/7.787;let x=.95047*fi(fx),y=fi(fy),z=1.08883*fi(fz);return[clamp(inv(x*3.2406+y*-1.5372+z*-.4986)),clamp(inv(x*-.9689+y*1.8758+z*.0415)),clamp(inv(x*.0557+y*-.204+z*1.057))];}
function ui(entries){const b=document.createElement("div");b.appendChild(pickerGroup(entries));return b;}
function select(label,value,items,on){const r=document.createElement("div");r.className="field";r.innerHTML=`<label>${label}</label><select class="grow">${items.map(([v,n])=>`<option value="${v}"${v===value?" selected":""}>${n}</option>`).join("")}</select>`;r.querySelector("select").onchange=e=>on(e.target.value);return r;}
function colorRow(label,value,on){const r=document.createElement("div");r.className="field";r.innerHTML=`<label>${label}</label><input type="color" value="${value}">`;r.querySelector("input").oninput=e=>on(e.target.value);return r;}
function hexRgb(h){return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];}
/* Coma flotante (fase 20): «true» = color puro (se evalúa en una rejilla); «delta» = local o que analiza la foto (su cambio se suma a los 16 bits).
   Umbral y Posterizar no: su resultado son pocos niveles y no conservan nada de los 16 bits. */
const FLOAT={"color-grading":true,"split-toning":true,"photo-filter":true,"lab-curves":true,"range-hsl":true,"replace-color":true,"desaturate":true,
  "dehaze":"delta","match-color":"delta","equalize":"delta","auto-tone-color":"delta","hdr-tone":"delta","tonal-contrast":"delta","graduated-filter":"delta"};
function base(title,id,p,compute,build,opts,float){return runAdjust({title,asLayer:true,filterId:id,filterParams:p,float:float!==undefined?float:FLOAT[id]||false,previewLimit:4e5,compute,buildBody:build},opts);}

function wheel(label,state,preview){const w=document.createElement("div");w.innerHTML=`<div class="section-label">${label}</div>`;const c=document.createElement("canvas");c.width=c.height=116;c.style.cssText="width:116px;height:116px;display:block;margin:auto;touch-action:none";w.appendChild(c);const paint=()=>{const x=c.getContext("2d"),im=x.createImageData(116,116),d=im.data,R=54;for(let y=0;y<116;y++)for(let xx=0;xx<116;xx++){const dx=xx-58,dy=y-58,r=Math.hypot(dx,dy),i=(y*116+xx)*4;if(r<=R){const [rr,g,b]=hslRgb((Math.atan2(dy,dx)*180/Math.PI+360)%360,r/R,.5);d[i]=rr;d[i+1]=g;d[i+2]=b;d[i+3]=255;}}x.putImageData(im,0,0);const a=state.h*Math.PI/180,rr=state.s*R;x.strokeStyle="#fff";x.lineWidth=2;x.beginPath();x.arc(58+Math.cos(a)*rr,58+Math.sin(a)*rr,5,0,Math.PI*2);x.stroke();};const set=e=>{const r=c.getBoundingClientRect(),dx=(e.clientX-r.left)*116/r.width-58,dy=(e.clientY-r.top)*116/r.height-58;state.h=(Math.atan2(dy,dx)*180/Math.PI+360)%360;state.s=Math.min(1,Math.hypot(dx,dy)/54);paint();preview();};c.onpointerdown=e=>{c.setPointerCapture(e.pointerId);set(e);};c.onpointermove=e=>{if(c.hasPointerCapture(e.pointerId))set(e);};paint();return w;}

export function colorGrading(opts={}){const p={sh:{h:220,s:0},mid:{h:30,s:0},hi:{h:45,s:0},mix:50,balance:0,...opts.init};
 return base("Gradación de color","color-grading",p,(d)=>{for(let i=0;i<d.length;i+=4){const l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255,b=p.balance/200,ws=clamp((.55+b-l)*3,0,1),wh=clamp((l-(.45+b))*3,0,1),wm=clamp(1-Math.abs(l-(.5+b))*3,0,1),sum=ws+wm+wh||1,m=p.mix/100;let [r,g,bb]=[d[i],d[i+1],d[i+2]];for(const [st,w] of [[p.sh,ws],[p.mid,wm],[p.hi,wh]]){const c=hslRgb(st.h,st.s,.5);r+=(c[0]-128)*w/sum*m;g+=(c[1]-128)*w/sum*m;bb+=(c[2]-128)*w/sum*m;}d[i]=clamp(r);d[i+1]=clamp(g);d[i+2]=clamp(bb);}},({preview})=>{const b=ui([{label:"Sombras",node:wheel("Sombras",p.sh,preview)},{label:"Medios",node:wheel("Medios",p.mid,preview)},{label:"Luces",node:wheel("Luces",p.hi,preview)},{label:"Mezcla",node:slider("Mezcla",0,100,p.mix,v=>{p.mix=v;preview();},"%")},{label:"Equilibrio",node:slider("Equilibrio",-100,100,p.balance,v=>{p.balance=v;preview();})}]);return b;},opts);}

export function splitToning(opts={}){const p={shadowHue:220,shadowSat:0,highlightHue:45,highlightSat:0,balance:0,...opts.init};return base("Virado dividido","split-toning",p,d=>{for(let i=0;i<d.length;i+=4){const l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255,t=clamp(l+p.balance/200,0,1),st=t<.5?{h:p.shadowHue,s:p.shadowSat/100,w:1-t*2}:{h:p.highlightHue,s:p.highlightSat/100,w:(t-.5)*2};const c=hslRgb(st.h,st.s,.5);for(let k=0;k<3;k++)d[i+k]=clamp(d[i+k]+(c[k]-128)*st.w);}},({preview})=>ui([{label:"Tono sombras",node:slider("Tono sombras",0,359,p.shadowHue,v=>{p.shadowHue=v;preview();},"°")},{label:"Saturación sombras",node:slider("Saturación sombras",0,100,p.shadowSat,v=>{p.shadowSat=v;preview();},"%")},{label:"Tono luces",node:slider("Tono luces",0,359,p.highlightHue,v=>{p.highlightHue=v;preview();},"°")},{label:"Saturación luces",node:slider("Saturación luces",0,100,p.highlightSat,v=>{p.highlightSat=v;preview();},"%")},{label:"Equilibrio",node:slider("Equilibrio",-100,100,p.balance,v=>{p.balance=v;preview();})}]),opts);}

const PHOTO={warm85:"#ec9f47",cool80:"#4a82d8",sepia:"#a66f3f",green:"#5ca66a",custom:"#f0a050"};
export function photoFilter(opts={}){const p={preset:"warm85",color:"#ec9f47",density:25,preserve:true,...opts.init};return base("Filtro fotográfico","photo-filter",p,d=>{const c=hexRgb(p.color),a=p.density/100;for(let i=0;i<d.length;i+=4){const lum=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];for(let k=0;k<3;k++)d[i+k]=d[i+k]*(1-a)+c[k]*a;if(p.preserve){const n=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2],q=lum/Math.max(1,n);for(let k=0;k<3;k++)d[i+k]=clamp(d[i+k]*q);}}},({preview})=>{const b=ui([{label:"Densidad",node:slider("Densidad",0,100,p.density,v=>{p.density=v;preview();},"%")}]);b.prepend(select("Filtro",p.preset,[["warm85","Cálido 85"],["cool80","Frío 80"],["sepia","Sepia"],["green","Verde"],["custom","Color libre"]],v=>{p.preset=v;if(v!=="custom")p.color=PHOTO[v];preview();}));b.appendChild(colorRow("Color",p.color,v=>{p.color=v;p.preset="custom";preview();}));const ck=document.createElement("label");ck.className="chk";ck.innerHTML='<input type="checkbox"> Conservar luminosidad';ck.querySelector("input").checked=p.preserve;ck.querySelector("input").onchange=e=>{p.preserve=e.target.checked;preview();};b.appendChild(ck);return b;},opts);}

function darkChannel(d,w,h,r=2){const out=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let m=255;for(let yy=Math.max(0,y-r);yy<=Math.min(h-1,y+r);yy++)for(let xx=Math.max(0,x-r);xx<=Math.min(w-1,x+r);xx++){const i=(yy*w+xx)*4;m=Math.min(m,d[i],d[i+1],d[i+2]);}out[y*w+x]=m;}return out;}
export function dehaze(opts={}){const p={amount:30,radius:2,...opts.init};return base("Quitar neblina","dehaze",p,(d,w,h)=>{const dc=darkChannel(d,w,h,p.radius);let a=0;for(const v of dc)if(v>a)a=v;const amt=p.amount/100;for(let n=0,i=0;n<dc.length;n++,i+=4){const t=clamp(1-Math.abs(amt)*.9*dc[n]/Math.max(1,a),.12,1);for(let k=0;k<3;k++){const clear=(d[i+k]-a)/t+a;d[i+k]=clamp(amt>=0?d[i+k]+(clear-d[i+k])*amt:d[i+k]+(a-d[i+k])*(-amt*.5));}}},({preview})=>ui([{label:"Cantidad",node:slider("Cantidad",-100,100,p.amount,v=>{p.amount=v;preview();},"%")},{label:"Radio local",node:slider("Radio local",1,5,p.radius,v=>{p.radius=v;preview();}," px")}]),opts);}

export function labCurves(opts={}){const p={channel:"l",points:{l:[[0,0],[255,255]],a:[[0,0],[255,255]],b:[[0,0],[255,255]]},...opts.init};return base("Curvas Lab / luminosidad","lab-curves",p,d=>{const L=curveLut(p.points.l),A=curveLut(p.points.a),B=curveLut(p.points.b);for(let i=0;i<d.length;i+=4){let [l,a,b]=rgbLab(d[i],d[i+1],d[i+2]);l=L[Math.round(clamp(l/100*255))]/255*100;a=A[Math.round(clamp(a+128))]-128;b=B[Math.round(clamp(b+128))]-128;[d[i],d[i+1],d[i+2]]=labRgb(l,a,b);}},({preview,hist})=>{const b=document.createElement("div"),host=document.createElement("div"),empty={l:hist?.l||new Uint32Array(256),a:new Uint32Array(256),b:new Uint32Array(256)};const render=()=>{host.innerHTML="";host.appendChild(curveEditor({getPoints:()=>p.points[p.channel],setPoints:v=>{p.points[p.channel]=v;preview();},hist:empty,channel:()=>p.channel}).el);};b.append(select("Canal",p.channel,[["l","Luminosidad L"],["a","Eje a · verde/magenta"],["b","Eje b · azul/amarillo"]],v=>{p.channel=v;render();}),host);render();return b;},opts);}

/* ── Tono, saturación y luminancia por rangos (mezclador HSL) ──
   Ocho rangos como en Lightroom. Cada píxel pesa en un rango según la
   distancia de su tono al centro, con una caída en coseno (sin saltos
   entre rangos vecinos), y según su CROMA: los grises, los blancos y
   los negros no tienen color y no los toca ningún rango (antes un
   gris contaba como «rojo», porque su tono vale 0, y aclarar los rojos
   aclaraba toda la imagen). La saturación es multiplicativa y la
   luminancia se acerca al blanco o al negro en proporción, así que
   ningún ajuste quema ni aplasta los tonos. */
/* Cuentagotas sobre la PROPIA imagen del documento (antes era una
   miniatura aparte, que además enseñaba el original y no el resultado):
   un toque en la imagen, por fuera del cuadro del diálogo, lee el color
   de ese punto en el original. Tocar fuera de la imagen sigue cerrando
   el diálogo, como siempre. En el móvil, la imagen se coloca encima de
   la hoja para ver los cambios en tiempo real. Devuelve una línea de
   ayuda para poner donde iba la miniatura. */
function pickOnImage(source,on){const note=document.createElement("p");note.className="hint";note.style.cssText="display:block!important;margin:4px 0 8px";note.textContent="Toca un color de la imagen para elegir su rango.";requestAnimationFrame(()=>{liftImageAbove(note);const back=note.closest(".modal");if(!back)return;back.style.cursor="crosshair";note._back=back;back.addEventListener("click",e=>{if(!note.isConnected||e.target!==back||!doc.open)return;const p=toImage(e.clientX,e.clientY);if(p.x<0||p.y<0||p.x>=doc.w||p.y>=doc.h)return;e.stopPropagation();const x=Math.min(source.width-1,Math.floor(p.x*source.width/doc.w)),y=Math.min(source.height-1,Math.floor(p.y*source.height/doc.h)),d=source.getContext("2d",{willReadFrequently:true}).getImageData(x,y,1,1).data;const [h,s]=rgbHsl(d[0],d[1],d[2]),chroma=(Math.max(d[0],d[1],d[2])-Math.min(d[0],d[1],d[2]))/255;on(h,chroma,s);},true);});return note;}
function sampleCanvas(source,on){const c=document.createElement("canvas"),W=280,H=Math.max(1,Math.round(W*source.height/source.width));c.width=W;c.height=H;c.style.cssText="display:block;margin:0 auto 8px;width:auto;height:auto;max-width:100%;max-height:150px;touch-action:none;cursor:crosshair";c.title="Toca un color de la foto para elegir su rango";c.getContext("2d").drawImage(source,0,0,W,H);c.onclick=e=>{const r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*W/r.width),y=Math.floor((e.clientY-r.top)*H/r.height),d=c.getContext("2d").getImageData(x,y,1,1).data;const [h,s]=rgbHsl(d[0],d[1],d[2]),chroma=(Math.max(d[0],d[1],d[2])-Math.min(d[0],d[1],d[2]))/255;on(h,chroma,s);};return c;}
/* Interfaz: cuentagotas + ocho círculos de color (el seleccionado lleva aro; un punto marca los rangos con cambios) y los mandos del rango elegido:
   Tono, Saturación, Luminancia, Difusión e Intervalo. El cuentagotas toca un color de la propia imagen: elige su rango y lo centra en ese tono.
   Premium 👑: el mismo ajuste en OKLCh (rangehsl.js). */
function dotsRow(p,onPick,onEyedrop,paint){const row=document.createElement("div");row.className="rh-dots";const eye=document.createElement("button");eye.type="button";eye.className="rh-eye";eye.title="Elegir un color de la imagen";eye.setAttribute("aria-label","Elegir un color de la imagen");eye.innerHTML='<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m2 22 1-1h3l9-9"/><path d="M3 21v-3l9-9"/><path d="m15 6 3.4-3.4a2.1 2.1 0 1 1 3 3L18 9l.4.4a2.1 2.1 0 1 1-3 3l-3.8-3.8a2.1 2.1 0 1 1 3-3z"/></svg>';eye.onclick=onEyedrop;row.appendChild(eye);const sep=document.createElement("span");sep.className="rh-sep";row.appendChild(sep);const btns={};for(const [k,n,h] of BANDS){const b=document.createElement("button");b.type="button";b.className="rh-dot";b.title=n;b.setAttribute("aria-label",n);b.style.setProperty("--c",`rgb(${hslRgb(h,.55,.42).map(Math.round).join(",")})`);b.onclick=()=>onPick(k);btns[k]=b;row.appendChild(b);}row.sync=()=>{for(const [k] of BANDS){const q=p.ranges[k];btns[k].classList.toggle("on",k===p.current);btns[k].classList.toggle("mod",!!(q.hue||q.sat||q.light));}};row.sync();return{row,eye};}
export function rangeHsl(opts={}){const init=opts.init||{},p={current:"red",premium:opts.init?false:premiumPref.get("rangeHsl"),...init,ranges:{...defaultRanges(),...(init.ranges||{})}};for(const q of Object.values(p.ranges))if(q.feather===undefined)q.feather=100;
 return base("Tono y saturación por rangos","range-hsl",p,(d,w,h)=>{if(p.premium)rangeHslPremium(d,p,{fast:w*h<doc.w*doc.h*.98});else rangeHslBasic(d,p);},({preview,source})=>{
  const b=document.createElement("div"),host=document.createElement("div");
  const sw=premiumSwitch({checked:p.premium,title:"Tono y saturación por rangos de alta calidad: OKLCh, luz lineal, mapeo de gama y tramado (función Premium)",onChange:on=>{p.premium=on;premiumPref.set("rangeHsl",on);preview();}});sw.classList.add("adj-premium");
  if(isMobile()){sw.classList.add("ps-docked");b.footStart=sw;}else b.appendChild(sw);
  let dots;const render=()=>{host.innerHTML="";const q=p.ranges[p.current];dots.row.sync();
   host.append(ui([{label:"Matiz",node:slider("Matiz",-100,100,q.hue,v=>{q.hue=v;dots.row.sync();preview();})},{label:"Saturación",node:slider("Saturación",-100,100,q.sat,v=>{q.sat=v;dots.row.sync();preview();},"%")},{label:"Luminancia",node:slider("Luminancia",-100,100,q.light,v=>{q.light=v;dots.row.sync();preview();},"%")},{label:"Difusión",node:slider("Difusión",0,100,q.feather,v=>{q.feather=v;preview();},"%")},{label:"Intervalo",node:slider("Intervalo",10,120,q.width,v=>{q.width=v;preview();},"°")}]));
   const reset=document.createElement("button");reset.type="button";reset.className="btn rh-reset";reset.textContent="Restablecer este color";reset.onclick=()=>{p.ranges[p.current]=defaultRanges()[p.current];preview();render();};host.append(reset);};
  let note=null;const stopPick=()=>{if(note){if(note._back)note._back.style.cursor="";note.remove();note=null;}dots.eye.classList.remove("on");};
  dots=dotsRow(p,k=>{p.current=k;stopPick();render();},()=>{if(note){stopPick();return;}dots.eye.classList.add("on");note=pickOnImage(source,(h,chroma)=>{if(chroma<.04){toast("Ese punto es gris: no pertenece a ningún rango de color");return;}const k=nearestBand(h);p.current=k;p.ranges[k].center=Math.round(h);stopPick();preview();render();});b.insertBefore(note,host);});
  b.append(dots.row,host);render();return b;},opts,()=>!p.premium);}
export function replaceColor(opts={}){const p={hue:0,tolerance:30,newHue:0,sat:0,light:0,...opts.init};return base("Reemplazar color","replace-color",p,d=>{for(let i=0;i<d.length;i+=4){let [h,s,l]=rgbHsl(d[i],d[i+1],d[i+2]),w=clamp(1-hueDist(h,p.hue)/Math.max(1,p.tolerance),0,1);h+=((p.newHue-h+540)%360-180)*w;s=clamp(s+p.sat/100*w,0,1);l=clamp(l+p.light/100*w,0,1);[d[i],d[i+1],d[i+2]]=hslRgb(h,s,l);}},({preview,source})=>{const b=ui([{label:"Tolerancia",node:slider("Tolerancia",1,120,p.tolerance,v=>{p.tolerance=v;preview();},"°")},{label:"Nuevo tono",node:slider("Nuevo tono",0,359,p.newHue,v=>{p.newHue=v;preview();},"°")},{label:"Saturación",node:slider("Saturación",-100,100,p.sat,v=>{p.sat=v;preview();},"%")},{label:"Luminosidad",node:slider("Luminosidad",-100,100,p.light,v=>{p.light=v;preview();},"%")}]);b.prepend(sampleCanvas(source,h=>{p.hue=h;preview();}));return b;},opts);}

function stats(canvas){const d=canvas.getContext("2d",{willReadFrequently:true}).getImageData(0,0,canvas.width,canvas.height).data,sum=[0,0,0],sq=[0,0,0];let n=0;for(let i=0;i<d.length;i+=4){if(!d[i+3])continue;const v=rgbLab(d[i],d[i+1],d[i+2]);for(let k=0;k<3;k++){sum[k]+=v[k];sq[k]+=v[k]*v[k];}n++;}n=Math.max(1,n);const mean=sum.map(x=>x/n),sd=sq.map((x,k)=>Math.sqrt(Math.max(1,x/n-mean[k]*mean[k])));return{mean,sd};}
export function matchColor(opts={}){const target=activeLayer(),fallback=target?stats(target.canvas):{mean:[50,0,0],sd:[20,20,20]},p={sourceId:null,sourceName:"",sourceStats:fallback,strength:100,...opts.init};return base("Igualar color","match-color",p,d=>{let sum=[0,0,0],sq=[0,0,0],n=0;for(let i=0;i<d.length;i+=4){if(!d[i+3])continue;const v=rgbLab(d[i],d[i+1],d[i+2]);for(let k=0;k<3;k++){sum[k]+=v[k];sq[k]+=v[k]*v[k];}n++;}n=Math.max(1,n);const m=sum.map(x=>x/n),s=sq.map((x,k)=>Math.sqrt(Math.max(1,x/n-m[k]*m[k]))),a=p.strength/100;for(let i=0;i<d.length;i+=4){if(!d[i+3])continue;let v=rgbLab(d[i],d[i+1],d[i+2]);for(let k=0;k<3;k++)v[k]+=((v[k]-m[k])*p.sourceStats.sd[k]/s[k]+p.sourceStats.mean[k]-v[k])*a;[d[i],d[i+1],d[i+2]]=labRgb(...v);}},({preview})=>{const layers=doc.layers.filter(l=>l.canvas&&l.type!=="group"&&l.id!==target?.id),b=ui([{label:"Intensidad",node:slider("Intensidad",0,100,p.strength,v=>{p.strength=v;preview();},"%")}]);if(layers.length)b.prepend(select("Capa de referencia",String(p.sourceId||layers[0].id),layers.map(l=>[String(l.id),l.name]),v=>{const l=layers.find(x=>String(x.id)===v);if(l){p.sourceId=l.id;p.sourceName=l.name;p.sourceStats=stats(l.canvas);preview();}}));const pick=document.createElement("button"),input=document.createElement("input"),note=document.createElement("small");pick.type="button";pick.className="btn";pick.textContent="Elegir otra imagen…";input.type="file";input.accept="image/*";input.hidden=true;note.textContent=p.sourceName?`Referencia: ${p.sourceName}`:"";pick.onclick=()=>input.click();input.onchange=()=>{const file=input.files?.[0];if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const scale=Math.min(1,Math.sqrt(1e6/(img.naturalWidth*img.naturalHeight))),c=document.createElement("canvas");c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));c.getContext("2d").drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);p.sourceId=null;p.sourceName=file.name;p.sourceStats=stats(c);note.textContent=`Referencia: ${file.name}`;preview();};img.onerror=()=>URL.revokeObjectURL(url);img.src=url;};b.prepend(pick,input,note);if(!p.sourceId&&!p.sourceName&&layers[0]){p.sourceId=layers[0].id;p.sourceName=layers[0].name;p.sourceStats=stats(layers[0].canvas);}return b;},opts);}

export function threshold(opts={}){const p={level:128,...opts.init};return base("Umbral","threshold",p,d=>{for(let i=0;i<d.length;i+=4){const v=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2]>=p.level?255:0;d[i]=d[i+1]=d[i+2]=v;}},({preview})=>ui([{label:"Umbral",node:slider("Umbral",0,255,p.level,v=>{p.level=v;preview();})}]),opts);}
export function posterize(opts={}){const p={levels:6,...opts.init};return base("Posterizar","posterize",p,d=>{const n=Math.max(2,p.levels),s=255/(n-1);for(let i=0;i<d.length;i+=4)for(let k=0;k<3;k++)d[i+k]=Math.round(d[i+k]/s)*s;},({preview})=>ui([{label:"Niveles",node:slider("Niveles",2,32,p.levels,v=>{p.levels=v;preview();})}]),opts);}
export function desaturate(opts={}){const p={amount:100,...opts.init};return base("Desaturar","desaturate",p,d=>{const a=p.amount/100;for(let i=0;i<d.length;i+=4){const l=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];for(let k=0;k<3;k++)d[i+k]+= (l-d[i+k])*a;}},({preview})=>ui([{label:"Cantidad",node:slider("Cantidad",0,100,p.amount,v=>{p.amount=v;preview();},"%")}]),opts);}
export function equalize(opts={}){const p={strength:100,...opts.init};return base("Ecualizar","equalize",p,d=>{const h=new Uint32Array(256),n=d.length/4;for(let i=0;i<d.length;i+=4)h[Math.round(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])]++;const c=new Uint32Array(256);c[0]=h[0];for(let i=1;i<256;i++)c[i]=c[i-1]+h[i];const a=p.strength/100;for(let i=0;i<d.length;i+=4){const l=Math.round(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2]),nl=c[l]/n*255,q=nl/Math.max(1,l);for(let k=0;k<3;k++)d[i+k]+= (clamp(d[i+k]*q)-d[i+k])*a;}},({preview})=>ui([{label:"Cantidad",node:slider("Cantidad",0,100,p.strength,v=>{p.strength=v;preview();},"%")}]),opts);}

/* Entrada «Premium 👑» del menú y del cajón: el mismo diálogo, con el interruptor ya encendido */
export const autoToneColorPremium=(opts={})=>autoToneColor({...opts,premium:true});
/* Premium 👑 (tonepremium.js): mismos mandos; estiramiento sobre la intensidad de cada color, neutros como balance de blancos en luz lineal, gama y tramado. Una capa ya hecha conserva su motor. */
export function autoToneColor(opts={}){const p={mode:"tone",clip:.5,neutral:true,mid:0,premium:opts.premium!==undefined?!!opts.premium:opts.init?false:premiumPref.get("autoToneColor"),...opts.init};return base("Tono / Color automático","auto-tone-color",p,(d,w,h)=>{if(p.premium){applyAutoToneColorPremium(d,w,h,p,{fast:w*h<doc.w*doc.h*.98});return;}const t=autoToneColorLuts(autoToneColorPlan(d,w,h,p));for(let i=0;i<d.length;i+=4){d[i]=t[0][d[i]];d[i+1]=t[1][d[i+1]];d[i+2]=t[2][d[i+2]];}},({preview})=>{const b=ui([{label:"Recorte",node:slider("Recorte por canal",0,5,p.clip,v=>{p.clip=v;preview();},"%",.1)},{label:"Medios",node:slider("Medios",-100,100,p.mid,v=>{p.mid=v;preview();})}]);b.prepend(select("Modo",p.mode,[["tone","Tono automático"],["color","Color automático"]],v=>{p.mode=v;preview();}));const ck=document.createElement("label");ck.className="chk";ck.innerHTML='<input type="checkbox"> Ajustar colores neutros';ck.querySelector("input").checked=p.neutral;ck.querySelector("input").onchange=e=>{p.neutral=e.target.checked;preview();};b.appendChild(ck);const sw=premiumSwitch({checked:p.premium,title:"Tono / Color automático de alta calidad: tono y saturación intactos, neutros equilibrados en luz lineal (función Premium)",onChange:on=>{p.premium=on;premiumPref.set("autoToneColor",on);preview();}});sw.classList.add("adj-premium");if(isMobile()){sw.classList.add("ps-docked");b.footStart=sw;}else b.prepend(sw);return b;},opts);}

function boxLum(d,w,h,r){const stride=w+1,integral=new Float64Array(stride*(h+1)),out=new Float32Array(w*h);for(let y=1;y<=h;y++){let row=0;for(let x=1;x<=w;x++){const i=((y-1)*w+x-1)*4;row+=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];integral[y*stride+x]=integral[(y-1)*stride+x]+row;}}for(let y=0;y<h;y++)for(let x=0;x<w;x++){const x0=Math.max(0,x-r),y0=Math.max(0,y-r),x1=Math.min(w-1,x+r)+1,y1=Math.min(h-1,y+r)+1,s=integral[y1*stride+x1]-integral[y0*stride+x1]-integral[y1*stride+x0]+integral[y0*stride+x0];out[y*w+x]=s/((x1-x0)*(y1-y0));}return out;}
export function hdrTone(opts={}){const p={compression:45,detail:35,glow:20,radius:3,...opts.init};return base("Tono HDR","hdr-tone",p,(d,w,h)=>{const av=boxLum(d,w,h,p.radius),c=p.compression/100,det=p.detail/100,g=p.glow/100;for(let n=0,i=0;n<av.length;n++,i+=4){const l=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2],base=128+(av[n]-128)*(1-c),nl=base+(l-av[n])*(1+det*2)+(av[n]-l)*g,q=nl/Math.max(1,l);for(let k=0;k<3;k++)d[i+k]=clamp(d[i+k]*q);}},({preview})=>ui([{label:"Compresión",node:slider("Compresión",0,100,p.compression,v=>{p.compression=v;preview();},"%")} ,{label:"Detalle",node:slider("Detalle",0,100,p.detail,v=>{p.detail=v;preview();},"%")},{label:"Resplandor",node:slider("Resplandor",0,100,p.glow,v=>{p.glow=v;preview();},"%")},{label:"Radio",node:slider("Radio",1,8,p.radius,v=>{p.radius=v;preview();}," px")}]),opts);}
export function tonalContrast(opts={}){const p={micro:25,medium:20,macro:10,...opts.init};return base("Contraste tonal","tonal-contrast",p,(d,w,h)=>{const a=boxLum(d,w,h,1),b=boxLum(d,w,h,3),c=boxLum(d,w,h,7);for(let n=0,i=0;n<a.length;n++,i+=4){const l=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2],nl=l+(l-a[n])*p.micro/100+(a[n]-b[n])*p.medium/100+(b[n]-c[n])*p.macro/100,q=nl/Math.max(1,l);for(let k=0;k<3;k++)d[i+k]=clamp(d[i+k]*q);}},({preview})=>ui([{label:"Microcontraste",node:slider("Microcontraste",-100,100,p.micro,v=>{p.micro=v;preview();},"%")},{label:"Contraste medio",node:slider("Contraste medio",-100,100,p.medium,v=>{p.medium=v;preview();},"%")},{label:"Macrocontraste",node:slider("Macrocontraste",-100,100,p.macro,v=>{p.macro=v;preview();},"%")}]),opts);}

export function graduatedFilter(opts={}){const p={kind:"linear",exposure:0,contrast:0,temp:0,centerX:50,centerY:50,size:55,angle:0,invert:false,...opts.init};return base("Densidad neutra graduada / radial","graduated-filter",p,(d,w,h)=>{const rad=p.angle*Math.PI/180,cx=w*p.centerX/100,cy=h*p.centerY/100,scale=Math.max(1,Math.min(w,h)*p.size/100),dx=Math.cos(rad),dy=Math.sin(rad),gain=Math.pow(2,p.exposure);for(let y=0,i=0;y<h;y++)for(let x=0;x<w;x++,i+=4){let m=p.kind==="radial"?1-Math.hypot(x-cx,y-cy)/scale:.5+((x-cx)*dx+(y-cy)*dy)/(scale*2);m=clamp(m,0,1);if(p.invert)m=1-m;let [r,g,b]=[d[i],d[i+1],d[i+2]],f=1+(gain-1)*m,ct=1+p.contrast/100*m;r=(r-128)*ct+128;g=(g-128)*ct+128;b=(b-128)*ct+128;r+=p.temp*1.1*m;b-=p.temp*1.1*m;d[i]=clamp(r*f);d[i+1]=clamp(g*f);d[i+2]=clamp(b*f);}},({preview})=>{const b=ui([{label:"Exposición",node:slider("Exposición",-3,3,p.exposure,v=>{p.exposure=v;preview();}," EV",.1)},{label:"Contraste",node:slider("Contraste",-100,100,p.contrast,v=>{p.contrast=v;preview();},"%")},{label:"Temperatura",node:slider("Temperatura",-100,100,p.temp,v=>{p.temp=v;preview();})},{label:"Centro X",node:slider("Centro X",0,100,p.centerX,v=>{p.centerX=v;preview();},"%")},{label:"Centro Y",node:slider("Centro Y",0,100,p.centerY,v=>{p.centerY=v;preview();},"%")},{label:"Extensión",node:slider("Extensión",5,150,p.size,v=>{p.size=v;preview();},"%")},{label:"Ángulo",node:slider("Ángulo",-180,180,p.angle,v=>{p.angle=v;preview();},"°")}]);b.prepend(select("Forma",p.kind,[["linear","Graduado lineal"],["radial","Filtro radial"]],v=>{p.kind=v;preview();}));const ck=document.createElement("label");ck.className="chk";ck.innerHTML='<input type="checkbox"> Invertir degradado';ck.querySelector("input").checked=p.invert;ck.querySelector("input").onchange=e=>{p.invert=e.target.checked;preview();};b.appendChild(ck);return b;},opts);}
