/* ═══════════════════════════════════════════════════════════════
   FILTRO VINTAGE · AJUSTES PREDEFINIDOS
   Sólo nombran los modificadores que usan; el resto queda a cero.
   Nombres descriptivos y genéricos, sin marcas comerciales.
   ═══════════════════════════════════════════════════════════════ */

export const PRESETS = [
  { id: "none", label: "Sin efecto", values: {} },

  { id: "slide60", label: "Diapositiva cálida años 60",
    values: { warmSlide: 75, rolloff: 45, grain: 25, vigOptical: 30, soft: 15, fade: 8 } },
  { id: "neg90", label: "Negativo frío años 90",
    values: { coolNeg: 70, grain: 35, fade: 18, rolloff: 35, vigOptical: 15 } },
  { id: "family70", label: "Álbum familiar años 70",
    values: { castYellow: 55, agedDesat: 45, fade: 40, rolloff: 50, grain: 40, soft: 25, vigOptical: 25, dust: 15 } },
  { id: "instant", label: "Instantánea desvaída",
    values: { fade: 50, split: 35, agedDesat: 35, rolloff: 60, instant: 60, soft: 30, vigOptical: 30, grain: 15 } },
  { id: "summer", label: "Verano quemado por el sol",
    values: { warmSlide: 50, leaks: 70, halation: 45, bloom: 30, fade: 25, grain: 30, vigOptical: 20 } },
  { id: "cross", label: "Proceso cruzado",
    values: { cross: 85, grain: 30, vigOptical: 35, lowRange: 25 } },
  { id: "expired", label: "Película caducada",
    values: { castMagenta: 55, fog: 35, fade: 35, grain: 60, agedDesat: 30, leaks: 20 } },
  { id: "xray", label: "Rayos X de aeropuerto",
    values: { fog: 75, castGreen: 25, grain: 45, agedDesat: 25, lowRange: 20 } },
  { id: "postcard", label: "Postal envejecida",
    values: { castYellow: 45, agedDesat: 60, fade: 35, paperBorder: 55, cracks: 35, stains: 25, soft: 20 } },
  { id: "cinema", label: "Cine nocturno",
    values: { halation: 70, split: 50, grain: 45, bloom: 35, lowRange: 20, vigOptical: 30 } },

  { id: "sepia1900", label: "Sepia de 1900",
    values: { sepia: 85, soft: 35, vigOptical: 55, fade: 20, dust: 35, scratches: 20, cracks: 20, grain: 25 } },
  { id: "cyanotype", label: "Cianotipia",
    values: { cyanotype: 90, soft: 25, paperBorder: 45, fade: 15, grain: 20 } },
  { id: "selenium", label: "Copia al selenio",
    values: { selenium: 85, rolloff: 30, grain: 30, vigOptical: 20 } },
  { id: "platinum", label: "Platino y paladio",
    values: { platinum: 90, fade: 20, rolloff: 45, soft: 20, paperBorder: 30 } },
  { id: "ortho1910", label: "Ortocromático de 1910",
    values: { panchro: 100, ortho: 95, lowRange: 30, soft: 40, vigOptical: 45, grain: 35, dust: 25 } },
  { id: "noir", label: "Noir de archivo",
    values: { panchro: 100, ortho: 60, lowRange: 45, grain: 55, scratches: 35, dust: 20, vigOptical: 40 } },
  { id: "daguerre", label: "Daguerrotipo desgastado",
    values: { platinum: 60, selenium: 25, vigMech: 55, soft: 55, cracks: 45, stains: 40, fog: 20 } },
  { id: "enlarger", label: "Copia de ampliadora",
    values: { panchro: 100, ortho: 40, paperBorder: 60, dust: 45, scratches: 25, grain: 30, rolloff: 25 } },
  { id: "scan35", label: "Negativo escaneado 35 mm",
    values: { filmBorder: 70, grain: 45, dust: 30, coolNeg: 30, fade: 15 } },

  { id: "toy", label: "Cámara de juguete",
    values: { vigMech: 60, soft: 40, ca: 50, leaks: 45, edgeBlur: 55, cross: 25, barrel: 30 } },
  { id: "petzval", label: "Objetivo de retrato antiguo",
    values: { swirl: 75, vigOptical: 45, edgeBlur: 35, soft: 20, warmSlide: 20 } },
  { id: "soviet", label: "Lente soviética",
    values: { swirl: 55, coma: 55, flare: 45, ca: 30, vigOptical: 30, bloom: 20 } },
  { id: "date98", label: "Compacta de 1998",
    values: { dateStamp: 90, warmSlide: 35, grain: 30, rolloff: 35, fade: 15, flare: 15 } },
  { id: "splitSoft", label: "Tonos partidos suaves",
    values: { split: 60, fade: 25, rolloff: 40, grain: 15 } },
  { id: "matte", label: "Mate contemporáneo",
    values: { fade: 55, agedDesat: 25, split: 20, grain: 20 } },
  { id: "nightShake", label: "Paseo nocturno a pulso",
    values: { shake: 55, halation: 45, bloom: 35, grain: 50, lowRange: 20 } },

  /* ── Décadas ── */
  { id: "d1920", cat: "Décadas", label: "Años 20: estudio de retrato",
    values: { sepia: 70, soft: 45, vigOptical: 60, fade: 15, dust: 30, cracks: 25, lowRange: 20, grain: 30 } },
  { id: "d1930", cat: "Décadas", label: "Años 30: noticiario",
    values: { panchro: 100, ortho: 70, lowRange: 35, grain: 60, scratches: 45, dust: 35, shake: 15, vigOptical: 35 } },
  { id: "d1940", cat: "Décadas", label: "Años 40: posguerra",
    values: { panchro: 100, ortho: 50, fade: 25, grain: 50, stains: 25, cracks: 20, soft: 30, vigOptical: 40, dust: 25 } },
  { id: "d1950", cat: "Décadas", label: "Años 50: primer color",
    values: { warmSlide: 45, agedDesat: 30, castYellow: 30, fade: 25, soft: 25, grain: 25, vigOptical: 25, rolloff: 40 } },
  { id: "d1950b", cat: "Décadas", label: "Años 50: anuncio de revista",
    values: { warmSlide: 55, castMagenta: 20, fade: 20, rolloff: 45, soft: 20, grain: 15 } },
  { id: "d1960b", cat: "Décadas", label: "Años 60: psicodelia",
    values: { cross: 55, warmSlide: 35, halation: 35, bloom: 30, grain: 30, vigOptical: 30, ca: 25 } },
  { id: "d1970b", cat: "Décadas", label: "Años 70: salón de casa",
    values: { castYellow: 65, fade: 35, agedDesat: 35, rolloff: 45, grain: 45, soft: 30, vigOptical: 20 } },
  { id: "d1970c", cat: "Décadas", label: "Años 70: verano en la costa",
    values: { warmSlide: 60, castYellow: 30, leaks: 35, fade: 30, grain: 35, rolloff: 55, bloom: 20 } },
  { id: "d1980", cat: "Décadas", label: "Años 80: flash directo",
    values: { coolNeg: 35, castMagenta: 25, lowRange: 30, grain: 30, vigOptical: 25, dateStamp: 40 } },
  { id: "d1980b", cat: "Décadas", label: "Años 80: neón y videoclub",
    values: { cross: 40, halation: 55, bloom: 40, split: 35, grain: 30, ca: 30 } },
  { id: "d1990b", cat: "Décadas", label: "Años 90: revelado de una hora",
    values: { coolNeg: 45, castGreen: 20, fade: 20, grain: 40, rolloff: 30, dateStamp: 55 } },
  { id: "d1990c", cat: "Décadas", label: "Años 90: desechable de fiesta",
    values: { coolNeg: 30, lowRange: 35, grain: 45, vigOptical: 35, flare: 20, soft: 20, dateStamp: 65 } },
  { id: "d2000", cat: "Décadas", label: "Años 2000: primera cámara digital",
    values: { coolNeg: 25, lowRange: 40, ca: 35, soft: 25, castGreen: 15, grain: 15 } },

  /* ── Películas en color ── */
  { id: "fReversalVivid", cat: "Películas en color", label: "Diapositiva saturada",
    values: { warmSlide: 85, lowRange: 20, rolloff: 25, grain: 15, vigOptical: 25 } },
  { id: "fReversalCool", cat: "Películas en color", label: "Diapositiva fría y limpia",
    values: { coolNeg: 55, lowRange: 15, rolloff: 25, grain: 12, vigOptical: 15 } },
  { id: "fPortrait", cat: "Películas en color", label: "Negativo de retrato suave",
    values: { warmSlide: 25, fade: 20, rolloff: 60, soft: 20, grain: 20, agedDesat: 15 } },
  { id: "fConsumer", cat: "Películas en color", label: "Negativo de consumo 200",
    values: { warmSlide: 35, castYellow: 20, grain: 35, rolloff: 40, fade: 12 } },
  { id: "fConsumerGreen", cat: "Películas en color", label: "Negativo verdoso 400",
    values: { coolNeg: 45, castGreen: 35, grain: 45, fade: 20, rolloff: 35 } },
  { id: "fTungsten", cat: "Películas en color", label: "Película de tungsteno de noche",
    values: { coolNeg: 70, halation: 55, bloom: 30, grain: 50, lowRange: 20 } },
  { id: "fCinemaNeg", cat: "Películas en color", label: "Negativo de cine",
    values: { split: 45, halation: 35, fade: 20, rolloff: 50, grain: 35 } },
  { id: "fBleach", cat: "Películas en color", label: "Blanqueo parcial (sin blanqueo)",
    values: { agedDesat: 60, lowRange: 45, grain: 45, coolNeg: 20, vigOptical: 25 } },
  { id: "fRedscale", cat: "Películas en color", label: "Película invertida (redscale)",
    values: { warmSlide: 90, castMagenta: 45, castYellow: 40, grain: 40, fade: 20, vigOptical: 30 } },
  { id: "fAerochrome", cat: "Películas en color", label: "Infrarrojo en falso color",
    values: { cross: 70, castMagenta: 60, halation: 30, grain: 30 } },
  { id: "fPushed", cat: "Películas en color", label: "Forzada dos pasos",
    values: { lowRange: 50, grain: 75, coolNeg: 25, vigOptical: 20, halation: 20 } },
  { id: "fPulled", cat: "Películas en color", label: "Subrevelada y lechosa",
    values: { fade: 55, agedDesat: 30, rolloff: 45, grain: 25, soft: 15 } },

  /* ── Blanco y negro ── */
  { id: "bwClassic", cat: "Blanco y negro", label: "Blanco y negro clásico",
    values: { panchro: 100, ortho: 30, grain: 35, rolloff: 25, vigOptical: 20 } },
  { id: "bwHighContrast", cat: "Blanco y negro", label: "Alto contraste de calle",
    values: { panchro: 100, ortho: 45, lowRange: 55, grain: 60, vigOptical: 25 } },
  { id: "bwSoft", cat: "Blanco y negro", label: "Gris suave de galería",
    values: { panchro: 100, platinum: 55, fade: 25, rolloff: 45, soft: 20, grain: 15 } },
  { id: "bwReportage", cat: "Blanco y negro", label: "Reportaje de guerra",
    values: { panchro: 100, ortho: 55, lowRange: 40, grain: 75, scratches: 30, dust: 25, shake: 15, vigOptical: 35 } },
  { id: "bwInfrared", cat: "Blanco y negro", label: "Infrarrojo en blanco y negro",
    values: { panchro: 100, ortho: 40, halation: 55, bloom: 50, grain: 45, fog: 15 } },
  { id: "bwNewsprint", cat: "Blanco y negro", label: "Foto de periódico",
    values: { panchro: 100, ortho: 50, lowRange: 45, fade: 30, grain: 70, soft: 25, stains: 15 } },
  { id: "bwFilmNoir", cat: "Blanco y negro", label: "Cine negro",
    values: { panchro: 100, ortho: 55, lowRange: 55, halation: 25, grain: 45, vigOptical: 55 } },
  { id: "bwContact", cat: "Blanco y negro", label: "Hoja de contactos",
    values: { panchro: 100, ortho: 35, filmBorder: 80, grain: 40, dust: 20 } },
  { id: "bwLith", cat: "Blanco y negro", label: "Copia lith",
    values: { panchro: 100, sepia: 45, lowRange: 40, grain: 65, fade: 15, vigOptical: 30 } },

  /* ── Procesos antiguos ── */
  { id: "pAlbumen", cat: "Procesos antiguos", label: "Albúmina del siglo XIX",
    values: { sepia: 65, castMagenta: 20, fade: 20, soft: 40, cracks: 35, stains: 30, vigOptical: 45 } },
  { id: "pTintype", cat: "Procesos antiguos", label: "Ferrotipo",
    values: { panchro: 100, platinum: 50, lowRange: 40, vigMech: 45, soft: 45, scratches: 25, stains: 35, ortho: 50 } },
  { id: "pAmbrotype", cat: "Procesos antiguos", label: "Ambrotipo",
    values: { selenium: 50, fog: 25, soft: 40, vigOptical: 55, cracks: 30, dust: 25 } },
  { id: "pGumPrint", cat: "Procesos antiguos", label: "Goma bicromatada",
    values: { sepia: 40, fade: 35, soft: 60, paperBorder: 50, stains: 25, grain: 30 } },
  { id: "pSaltPrint", cat: "Procesos antiguos", label: "Papel a la sal",
    values: { sepia: 55, castYellow: 20, fade: 40, soft: 45, paperBorder: 40, vigOptical: 35 } },
  { id: "pCyanFaded", cat: "Procesos antiguos", label: "Cianotipia desvaída",
    values: { cyanotype: 65, fade: 40, paperBorder: 55, stains: 20, soft: 20 } },
  { id: "pAutochrome", cat: "Procesos antiguos", label: "Autocromo de 1910",
    values: { agedDesat: 35, warmSlide: 25, grain: 80, soft: 40, vigOptical: 45, castGreen: 15 } },
  { id: "pHandColored", cat: "Procesos antiguos", label: "Coloreada a mano",
    values: { sepia: 30, agedDesat: 45, warmSlide: 30, fade: 25, soft: 30, paperBorder: 35 } },
  { id: "pGlassPlate", cat: "Procesos antiguos", label: "Placa de vidrio",
    values: { panchro: 100, ortho: 70, soft: 35, vigOptical: 50, cracks: 40, dust: 40, stains: 20, fog: 15 } },

  /* ── Cámaras y ópticas ── */
  { id: "cBox", cat: "Cámaras y ópticas", label: "Cámara de cajón",
    values: { vigMech: 50, soft: 50, edgeBlur: 45, barrel: 20, sepia: 25, grain: 30 } },
  { id: "cTLR", cat: "Cámaras y ópticas", label: "Formato medio bireflex",
    values: { vigOptical: 30, rolloff: 45, grain: 25, warmSlide: 20, filmBorder: 25 } },
  { id: "cHalfFrame", cat: "Cámaras y ópticas", label: "Medio formato de bolsillo",
    values: { grain: 55, soft: 25, vigOptical: 35, warmSlide: 25, leaks: 25 } },
  { id: "cPinhole", cat: "Cámaras y ópticas", label: "Estenopeica",
    values: { soft: 70, vigOptical: 70, edgeBlur: 40, grain: 35, fade: 15 } },
  { id: "cPlasticLens", cat: "Cámaras y ópticas", label: "Lente de plástico",
    values: { soft: 45, ca: 60, bloom: 40, vigOptical: 45, leaks: 30 } },
  { id: "cFisheye", cat: "Cámaras y ópticas", label: "Ojo de pez de juguete",
    values: { barrel: 85, vigMech: 55, ca: 35, soft: 20, cross: 25 } },
  { id: "cTiltShift", cat: "Cámaras y ópticas", label: "Miniatura (desenfoque de bordes)",
    values: { edgeBlur: 80, warmSlide: 30, lowRange: 20 } },
  { id: "cSoftFocus", cat: "Cámaras y ópticas", label: "Filtro de difusión de estudio",
    values: { bloom: 60, soft: 35, rolloff: 50, halation: 25, fade: 10 } },
  { id: "cUncoated", cat: "Cámaras y ópticas", label: "Lente sin tratamiento a contraluz",
    values: { flare: 70, bloom: 55, fog: 25, halation: 30 } },
  { id: "cSuper8", cat: "Cámaras y ópticas", label: "Fotograma de súper 8",
    values: { warmSlide: 45, grain: 70, soft: 35, vigMech: 35, scratches: 30, dust: 30, shake: 20 } },
  { id: "cVHS", cat: "Cámaras y ópticas", label: "Captura de cinta de vídeo",
    values: { ca: 55, soft: 45, lowRange: 30, coolNeg: 25, grain: 30, shake: 15, dateStamp: 40 } },

  /* ── Creativos ── */
  { id: "xDreamy", cat: "Creativos", label: "Soñadora",
    values: { bloom: 60, fade: 35, split: 30, soft: 30, leaks: 25, rolloff: 50 } },
  { id: "xMoody", cat: "Creativos", label: "Melancólica",
    values: { coolNeg: 40, agedDesat: 40, fade: 30, lowRange: 20, vigOptical: 40, grain: 30 } },
  { id: "xGolden", cat: "Creativos", label: "Hora dorada",
    values: { warmSlide: 70, leaks: 40, halation: 30, bloom: 30, rolloff: 45, grain: 20 } },
  { id: "xBurntFilm", cat: "Creativos", label: "Película quemada",
    values: { leaks: 90, halation: 45, fade: 25, grain: 45, scratches: 25, filmBorder: 35 } },
  { id: "xDamaged", cat: "Creativos", label: "Archivo muy dañado",
    values: { agedDesat: 50, fade: 40, dust: 70, scratches: 60, stains: 55, cracks: 55, grain: 50 } },
  { id: "xFoundPhoto", cat: "Creativos", label: "Foto encontrada en un mercadillo",
    values: { castYellow: 50, agedDesat: 50, fade: 45, paperBorder: 60, stains: 35, cracks: 30, instant: 20 } },
  { id: "xPolaroidCool", cat: "Creativos", label: "Instantánea fría",
    values: { coolNeg: 45, fade: 40, instant: 55, soft: 25, vigOptical: 25, rolloff: 50 } },
  { id: "xPolaroidWarm", cat: "Creativos", label: "Instantánea cálida",
    values: { warmSlide: 50, fade: 35, instant: 60, soft: 25, vigOptical: 25, rolloff: 55 } },
  { id: "xGhost", cat: "Creativos", label: "Fantasmagórica",
    values: { shake: 70, fog: 35, agedDesat: 50, bloom: 30, vigOptical: 45 } },
  { id: "xKodachromeLike", cat: "Creativos", label: "Postal de viaje saturada",
    values: { warmSlide: 70, lowRange: 25, vigOptical: 30, paperBorder: 30, grain: 15 } },
  { id: "xNightClub", cat: "Creativos", label: "Discoteca con flash",
    values: { cross: 45, halation: 50, lowRange: 35, grain: 40, ca: 25, vigOptical: 30 } },
  { id: "xRainyCity", cat: "Creativos", label: "Ciudad lluviosa",
    values: { coolNeg: 55, halation: 40, bloom: 30, fade: 20, grain: 35, split: 25 } },

  /* ── Estaciones y ambientes ── */
  { id: "sAutumn", cat: "Estaciones y ambientes", label: "Otoño",
    values: { warmSlide: 55, castYellow: 30, agedDesat: 15, fade: 20, grain: 25, vigOptical: 25 } },
  { id: "sWinter", cat: "Estaciones y ambientes", label: "Invierno",
    values: { coolNeg: 60, agedDesat: 25, fade: 25, rolloff: 45, grain: 20 } },
  { id: "sSpring", cat: "Estaciones y ambientes", label: "Primavera",
    values: { split: 35, fade: 25, bloom: 30, rolloff: 45, soft: 15 } },
  { id: "sBeach", cat: "Estaciones y ambientes", label: "Playa al mediodía",
    values: { warmSlide: 45, fade: 30, rolloff: 60, bloom: 25, grain: 20 } },
  { id: "sForest", cat: "Estaciones y ambientes", label: "Bosque húmedo",
    values: { coolNeg: 35, castGreen: 40, fade: 20, soft: 20, vigOptical: 35, grain: 25 } },
  { id: "sDesert", cat: "Estaciones y ambientes", label: "Desierto polvoriento",
    values: { castYellow: 55, fog: 30, fade: 30, grain: 40, dust: 35 } },
  { id: "sMountain", cat: "Estaciones y ambientes", label: "Montaña de postal",
    values: { coolNeg: 30, lowRange: 20, vigOptical: 30, paperBorder: 40, grain: 20 } },
  { id: "sCandle", cat: "Estaciones y ambientes", label: "Luz de velas",
    values: { warmSlide: 75, halation: 45, bloom: 35, grain: 45, vigOptical: 40, lowRange: 20 } },
  { id: "sFog", cat: "Estaciones y ambientes", label: "Niebla matinal",
    values: { fog: 55, fade: 30, agedDesat: 30, soft: 25, rolloff: 40 } }
];


/* ── Estilos añadidos en la v148: nuevas categorías y estilos con marco
   (`frame` = id de frames.js; el marco forma parte del estilo). ── */
const P = (cat, id, label, values, frame) => ({ id, cat, label, values, ...(frame ? { frame } : {}) });
PRESETS.push(
  /* Laboratorio y revelado */
  P("Laboratorio y revelado", "labPush", "Forzado dos pasos", { lowRange: 55, grain: 75, panchro: 100, vigOptical: 25 }),
  P("Laboratorio y revelado", "labPull", "Revelado corto y suave", { fade: 35, rolloff: 60, grain: 20, agedDesat: 25 }),
  P("Laboratorio y revelado", "labBleach", "Blanqueo parcial", { agedDesat: 65, lowRange: 55, grain: 40, split: 15 }),
  P("Laboratorio y revelado", "labTired", "Químicos agotados", { castYellow: 40, fog: 30, stains: 45, fade: 25, grain: 35 }),
  P("Laboratorio y revelado", "labSolar", "Efecto Sabattier", { panchro: 100, cross: 35, fog: 25, lowRange: 40, halation: 30 }),
  P("Laboratorio y revelado", "labHot", "Revelador demasiado caliente", { castMagenta: 35, grain: 65, fog: 20, lowRange: 25, cracks: 15 }),
  P("Laboratorio y revelado", "labContact", "Hoja de contactos", { panchro: 100, grain: 35, dust: 30, fade: 10 }, "film35"),
  P("Laboratorio y revelado", "labTest", "Tira de prueba", { panchro: 100, ortho: 20, fog: 20, grain: 40, stains: 25 }, "filmFiledWhite"),
  P("Laboratorio y revelado", "labDarkroom", "Luz roja del cuarto oscuro", { selenium: 40, castMagenta: 50, lowRange: 30, grain: 30, vigOptical: 35 }),
  P("Laboratorio y revelado", "labLith", "Copia lith", { sepia: 60, lowRange: 45, grain: 60, rolloff: 20, vigOptical: 25 }),

  /* Cine clásico */
  P("Cine clásico", "cineTechni", "Tres bandas de color", { warmSlide: 60, lowRange: 30, halation: 25, bloom: 20, grain: 20 }),
  P("Cine clásico", "cineWestern", "Western polvoriento", { castYellow: 55, fade: 25, dust: 35, scratches: 30, grain: 40, vigOptical: 30 }),
  P("Cine clásico", "cineSilent", "Cine mudo", { panchro: 100, ortho: 70, shake: 20, scratches: 60, dust: 50, vigOptical: 55, soft: 30 }, "filmCine"),
  P("Cine clásico", "cineNouvelle", "Nueva ola francesa", { panchro: 100, grain: 50, lowRange: 25, soft: 15 }),
  P("Cine clásico", "cineGiallo", "Giallo italiano", { castMagenta: 35, warmSlide: 45, halation: 55, bloom: 35, grain: 35 }),
  P("Cine clásico", "cineScifi70", "Ciencia ficción de los 70", { coolNeg: 50, bloom: 45, flare: 55, grain: 35, fade: 20 }),
  P("Cine clásico", "cineMusical", "Musical en color", { warmSlide: 70, bloom: 40, halation: 30, rolloff: 30 }),
  P("Cine clásico", "cineNoirRain", "Detective bajo la lluvia", { panchro: 100, lowRange: 55, halation: 40, grain: 50, vigOptical: 45 }),
  P("Cine clásico", "cineDrive", "Autocine", { cross: 30, halation: 50, fade: 20, grain: 35, vigOptical: 30 }, "projector"),
  P("Cine clásico", "cineTrailer", "Tráiler rayado", { warmSlide: 40, scratches: 70, dust: 55, grain: 45, fade: 20 }, "leader"),
  P("Cine clásico", "cineS8", "Vacaciones en súper 8", { warmSlide: 55, leaks: 45, grain: 60, soft: 30, shake: 20, vigOptical: 35 }, "filmS8"),

  /* Viajes y postales */
  P("Viajes y postales", "tRiviera", "Riviera de 1960", { warmSlide: 65, fade: 20, rolloff: 45, grain: 20 }, "postcard"),
  P("Viajes y postales", "tSafari", "Safari", { castYellow: 60, fog: 20, grain: 40, vigOptical: 35, dust: 20 }),
  P("Viajes y postales", "tAlps", "Postal alpina", { coolNeg: 40, lowRange: 20, paperBorder: 20, grain: 15 }, "deckleWhite"),
  P("Viajes y postales", "tRoute", "Carretera americana", { warmSlide: 55, fade: 25, halation: 25, grain: 30, leaks: 20 }),
  P("Viajes y postales", "tAirmail", "Carta desde lejos", { castYellow: 35, agedDesat: 35, fade: 25, grain: 20 }, "airmail"),
  P("Viajes y postales", "tStamp", "Sello de colección", { agedDesat: 45, castYellow: 30, lowRange: 25, soft: 20 }, "stamp"),
  P("Viajes y postales", "tPostmark", "Matasellos", { sepia: 40, agedDesat: 30, fade: 25, stains: 20 }, "postmark"),
  P("Viajes y postales", "tTropic", "Trópico saturado", { warmSlide: 55, cross: 20, bloom: 25, grain: 15 }),
  P("Viajes y postales", "tSlideShow", "Proyección de diapositivas", { warmSlide: 60, vigOptical: 40, dust: 25, soft: 15 }, "slideWhite"),
  P("Viajes y postales", "tSouvenir", "Recuerdo en la maleta", { castYellow: 40, fade: 30, cracks: 25, stains: 20 }, "scallop"),

  /* Retratos antiguos */
  P("Retratos antiguos", "rCabinet", "Retrato de estudio 1890", { sepia: 80, soft: 35, vigOptical: 45, cracks: 20, fade: 15 }, "cabinet"),
  P("Retratos antiguos", "rCdv", "Carte de visite", { sepia: 70, platinum: 20, soft: 30, dust: 20, fade: 20 }, "cdv"),
  P("Retratos antiguos", "rCameo", "Camafeo victoriano", { sepia: 65, soft: 40, vigOptical: 30, grain: 20 }, "cameo"),
  P("Retratos antiguos", "rOval", "Óvalo de la abuela", { sepia: 55, fade: 30, soft: 35, stains: 20 }, "ovalMat"),
  P("Retratos antiguos", "rTintype", "Ferrotipo", { platinum: 50, selenium: 40, lowRange: 40, vigMech: 35, cracks: 30, soft: 35 }, "ovalDark"),
  P("Retratos antiguos", "rAmbro", "Ambrotipo en estuche", { selenium: 55, platinum: 30, vigOptical: 55, soft: 40, cracks: 25 }, "goldOrnate"),
  P("Retratos antiguos", "rWedding", "Boda de 1920", { sepia: 55, rolloff: 50, soft: 35, bloom: 25, fade: 20 }, "matOval"),
  P("Retratos antiguos", "rSoldier", "Retrato de uniforme", { sepia: 75, ortho: 30, panchro: 100, grain: 35, cracks: 30, stains: 25 }, "albumen"),
  P("Retratos antiguos", "rHollywood", "Galán de estudio", { panchro: 100, bloom: 40, rolloff: 45, soft: 30, vigOptical: 35 }),
  P("Retratos antiguos", "rChild", "Primera comunión", { sepia: 40, fade: 35, rolloff: 50, soft: 30 }, "lace"),

  /* Instantáneas */
  P("Instantáneas", "iClassic", "Instantánea clásica", { fade: 35, split: 30, rolloff: 55, instant: 40, soft: 20 }, "instWhite"),
  P("Instantáneas", "iExpired", "Instantánea caducada", { castYellow: 45, fade: 45, fog: 25, instant: 75, agedDesat: 30 }, "instCream"),
  P("Instantáneas", "iBlack", "Edición negra", { lowRange: 30, split: 35, rolloff: 45, grain: 20 }, "instBlack"),
  P("Instantáneas", "iPink", "Pastel rosa", { castMagenta: 25, fade: 40, rolloff: 55, bloom: 20 }, "instPink"),
  P("Instantáneas", "iMint", "Menta fresca", { castGreen: 25, fade: 35, rolloff: 45, split: 20 }, "instMint"),
  P("Instantáneas", "iSky", "Celeste de verano", { coolNeg: 35, fade: 35, bloom: 20, rolloff: 50 }, "instSky"),
  P("Instantáneas", "iSquare", "Cuadrada con cinta", { fade: 30, split: 30, instant: 30, grain: 15 }, "instTape"),
  P("Instantáneas", "iMono", "Instantánea en blanco y negro", { panchro: 100, fade: 30, rolloff: 45, instant: 35 }, "instWhite"),
  P("Instantáneas", "iNote", "Con dedicatoria", { castYellow: 30, fade: 35, split: 25, rolloff: 45 }, "instNote"),
  P("Instantáneas", "iCoffee", "Olvidada en la mesa", { castYellow: 45, fade: 40, stains: 35, agedDesat: 30 }, "instCoffee"),
  P("Instantáneas", "iWide", "Panorámica de fiesta", { warmSlide: 30, halation: 30, fade: 25, flare: 20 }, "instWide"),

  /* Álbum de familia */
  P("Álbum de familia", "fAlbum60", "Álbum de los 60", { castYellow: 45, agedDesat: 40, fade: 30, grain: 25 }, "cornersBlack"),
  P("Álbum de familia", "fAlbum70", "Álbum de los 70", { warmSlide: 45, castYellow: 30, fade: 35, grain: 30 }, "scallop"),
  P("Álbum de familia", "fAlbum80", "Álbum de los 80", { coolNeg: 35, castMagenta: 25, fade: 25, grain: 30, dateStamp: 50 }, "cornersGold"),
  P("Álbum de familia", "fBirthday", "Cumpleaños con flash", { warmSlide: 30, halation: 35, lowRange: 30, vigOptical: 30, grain: 25 }),
  P("Álbum de familia", "fChristmas", "Navidad de 1975", { warmSlide: 55, halation: 40, bloom: 30, grain: 35, fade: 20 }, "wave"),
  P("Álbum de familia", "fBeach", "Verano en la playa", { warmSlide: 50, fade: 35, rolloff: 55, leaks: 25 }, "deckleCream"),
  P("Álbum de familia", "fAttic", "Encontrada en el desván", { castYellow: 50, agedDesat: 50, dust: 45, stains: 35, cracks: 30 }, "wornCorners"),
  P("Álbum de familia", "fScrap", "Cuaderno de recuerdos", { fade: 30, castYellow: 30, grain: 20 }, "scrapbook"),
  P("Álbum de familia", "fWashi", "Álbum decorado", { fade: 25, split: 25, rolloff: 40 }, "washi"),
  P("Álbum de familia", "fDrawer", "Cajón de fotos sueltas", { castMagenta: 40, agedDesat: 40, fade: 35, dust: 25 }, "zigzag"),

  /* Noir y misterio */
  P("Noir y misterio", "nKeyhole", "Por la cerradura", { panchro: 100, lowRange: 45, grain: 45 }, "keyhole"),
  P("Noir y misterio", "nSpy", "Prismáticos del espía", { panchro: 100, grain: 50, soft: 25 }, "binoculars"),
  P("Noir y misterio", "nCase", "Expediente policial", { panchro: 100, ortho: 40, fade: 20, stains: 30, grain: 40 }, "kraft"),
  P("Noir y misterio", "nFog", "Niebla en el puerto", { panchro: 100, fog: 45, grain: 45, halation: 30, vigOptical: 40 }),
  P("Noir y misterio", "nSmoke", "Club de jazz", { selenium: 45, bloom: 45, halation: 45, grain: 50, vigOptical: 45 }),
  P("Noir y misterio", "nMoon", "Luna de sangre", { panchro: 100, castMagenta: 30, lowRange: 50, grain: 40, vigMech: 30 }),
  P("Noir y misterio", "nGhost", "Fotografía espiritista", { platinum: 60, shake: 55, bloom: 40, fog: 30, vigOptical: 50 }, "ovalSepia"),
  P("Noir y misterio", "nBurnt", "Rescatada del incendio", { sepia: 60, lowRange: 35, stains: 40, cracks: 35, grain: 30 }, "burnt"),
  P("Noir y misterio", "nPinhole", "Estenopeica nocturna", { panchro: 100, soft: 55, grain: 55, lowRange: 25 }, "pinhole"),
  P("Noir y misterio", "nTelegram", "Telegrama urgente", { sepia: 40, agedDesat: 40, fade: 30, grain: 25 }, "telegram"),

  /* Pop y psicodelia */
  P("Pop y psicodelia", "pFlower", "Flower power", { cross: 55, warmSlide: 30, bloom: 30, grain: 25 }, "floral"),
  P("Pop y psicodelia", "pRainbow", "Arcoíris setentero", { warmSlide: 55, fade: 30, halation: 30, grain: 25 }, "rainbow70"),
  P("Pop y psicodelia", "pNeon", "Neón ochentero", { cross: 45, halation: 60, bloom: 40, coolNeg: 20 }, "neon80"),
  P("Pop y psicodelia", "pAcid", "Viaje ácido", { cross: 90, swirl: 40, ca: 45, bloom: 30 }),
  P("Pop y psicodelia", "pCandy", "Tienda de caramelos", { warmSlide: 40, castMagenta: 25, fade: 25, bloom: 25 }, "candy"),
  P("Pop y psicodelia", "pPolka", "Lunares pop", { cross: 35, lowRange: 30, grain: 20 }, "polka"),
  P("Pop y psicodelia", "pStars", "Noche estrellada", { coolNeg: 50, halation: 40, bloom: 30, grain: 30 }, "stars"),
  P("Pop y psicodelia", "pChecker", "Ska y cuadros", { panchro: 100, lowRange: 40, grain: 30 }, "checker"),
  P("Pop y psicodelia", "pZigzag", "Memphis 1985", { cross: 40, fade: 25, bloom: 20 }, "zigzagColor"),
  P("Pop y psicodelia", "pHeart", "San Valentín", { castMagenta: 30, bloom: 35, fade: 30, rolloff: 45 }, "heart"),

  /* Tecnología retro */
  P("Tecnología retro", "tvCrt", "Televisor de tubo", { bloom: 30, ca: 40, soft: 30, lowRange: 20, vigOptical: 30 }, "crt"),
  P("Tecnología retro", "tvPhosphor", "Monitor de fósforo verde", { panchro: 100, castGreen: 60, bloom: 35, soft: 25 }, "crtGreen"),
  P("Tecnología retro", "tvCamcorder", "Videocámara familiar", { coolNeg: 30, ca: 45, soft: 35, grain: 30, bloom: 20 }, "camcorder"),
  P("Tecnología retro", "tvVhs", "Cinta VHS gastada", { ca: 55, soft: 40, castMagenta: 20, fade: 25, shake: 15 }, "vhs"),
  P("Tecnología retro", "tvViewfinder", "Visor réflex", { warmSlide: 25, vigOptical: 35, soft: 10 }, "viewfinder"),
  P("Tecnología retro", "tvRange", "Telémetro de 1965", { panchro: 100, grain: 40, vigOptical: 30 }, "rangefinder"),
  P("Tecnología retro", "tvDigicam", "Cámara digital de 2003", { coolNeg: 25, ca: 35, lowRange: 40, soft: 15, dateStamp: 70 }),
  P("Tecnología retro", "tvPhone", "Móvil con tapa", { soft: 55, ca: 40, grain: 50, lowRange: 35, castGreen: 20 }),
  P("Tecnología retro", "tvScanner", "Escáner de sobremesa", { fade: 20, dust: 40, agedDesat: 25, soft: 20 }, "floating"),
  P("Tecnología retro", "tvFax", "Fax recibido", { panchro: 100, lowRange: 70, grain: 70, scratches: 30 }, "grungeWhite"),

  /* Galería y museo */
  P("Galería y museo", "gOldMaster", "Viejo maestro", { warmSlide: 40, castYellow: 30, lowRange: 30, cracks: 40, vigOptical: 40 }, "gold"),
  P("Galería y museo", "gBaroque", "Salón barroco", { warmSlide: 45, cracks: 35, vigOptical: 50, soft: 15 }, "goldOrnate"),
  P("Galería y museo", "gMuseum", "Sala de museo", { platinum: 60, fade: 15, rolloff: 40 }, "goldMuseum"),
  P("Galería y museo", "gSilver", "Plata antigua", { selenium: 70, rolloff: 35, grain: 20 }, "silver"),
  P("Galería y museo", "gWalnut", "Salón de nogal", { sepia: 50, fade: 20, vigOptical: 30, grain: 20 }, "woodDark"),
  P("Galería y museo", "gCottage", "Casa de campo", { castYellow: 35, fade: 25, grain: 25 }, "woodRustic"),
  P("Galería y museo", "gDeco", "Gran hotel déco", { panchro: 100, selenium: 30, lowRange: 35, bloom: 20 }, "artDeco"),
  P("Galería y museo", "gGallery", "Galería contemporánea", { split: 30, fade: 20, rolloff: 35 }, "gallery"),
  P("Galería y museo", "gVelvet", "Palacio de terciopelo", { warmSlide: 50, halation: 30, vigOptical: 40 }, "redVelvet"),
  P("Galería y museo", "gNouveau", "Modernismo", { sepia: 35, castGreen: 20, fade: 25, soft: 20 }, "nouveau"),
  P("Galería y museo", "gShadowbox", "Vitrina", { platinum: 40, fade: 15 }, "shadowbox"),

  /* Papel y archivo */
  P("Papel y archivo", "aTorn", "Página arrancada", { sepia: 45, agedDesat: 35, stains: 30, grain: 20 }, "torn"),
  P("Papel y archivo", "aWater", "Inundación del archivo", { castYellow: 50, stains: 55, agedDesat: 45, fog: 20 }, "water"),
  P("Papel y archivo", "aMold", "Sótano húmedo", { castGreen: 40, agedDesat: 45, stains: 40, fade: 25 }, "mold"),
  P("Papel y archivo", "aKraft", "Sobre de papel madera", { sepia: 35, fade: 30, grain: 25 }, "kraft"),
  P("Papel y archivo", "aLabel", "Botica antigua", { sepia: 55, fade: 25, soft: 20 }, "label"),
  P("Papel y archivo", "aEmboss", "Cartón gofrado", { platinum: 55, fade: 20, rolloff: 40 }, "emboss"),
  P("Papel y archivo", "aGreek", "Álbum de viaje a Grecia", { warmSlide: 45, fade: 30, grain: 20 }, "greek"),
  P("Papel y archivo", "aTiles", "Azulejo portugués", { cyanotype: 60, fade: 20 }, "tiles"),
  P("Papel y archivo", "aDusty", "Negativo polvoriento", { coolNeg: 30, dust: 60, scratches: 30, grain: 35 }, "dusty"),
  P("Papel y archivo", "aScratched", "Placa rayada", { panchro: 100, scratches: 55, dust: 35, grain: 35 }, "scratchedBlack")
);

/* Categoría de cada estilo para agruparlos en el desplegable. Los
   originales no la declaran: van a «Clásicos» (salvo los procesos B/N
   y de ópticas, que se reparten en sus grupos). */
const ORIGINAL_CATS = { sepia1900: "Procesos antiguos", cyanotype: "Procesos antiguos", selenium: "Procesos antiguos",
  platinum: "Procesos antiguos", daguerre: "Procesos antiguos", ortho1910: "Blanco y negro", noir: "Blanco y negro",
  enlarger: "Blanco y negro", toy: "Cámaras y ópticas", petzval: "Cámaras y ópticas", soviet: "Cámaras y ópticas",
  date98: "Décadas", slide60: "Décadas", neg90: "Décadas", family70: "Décadas", scan35: "Películas en color",
  cross: "Películas en color", expired: "Películas en color", xray: "Películas en color" };
for(const p of PRESETS) if(!p.cat) p.cat = p.id === "none" ? "" : ORIGINAL_CATS[p.id] || "Clásicos";
export const PRESET_CATS = ["Clásicos", "Décadas", "Películas en color", "Blanco y negro", "Procesos antiguos", "Cámaras y ópticas", "Creativos", "Estaciones y ambientes",
  "Laboratorio y revelado", "Cine clásico", "Viajes y postales", "Retratos antiguos", "Instantáneas", "Álbum de familia", "Noir y misterio",
  "Pop y psicodelia", "Tecnología retro", "Galería y museo", "Papel y archivo"];

export const preset = id => PRESETS.find(p => p.id === id);
