/* ═══════════════════════════════════════════════════════════════
   FILTRO VINTAGE · AJUSTES PREDEFINIDOS
   Sólo nombran los modificadores que usan; el resto queda a cero.
   Nombres descriptivos y genéricos, sin marcas comerciales.
   ═══════════════════════════════════════════════════════════════ */

export const PRESETS = [
  { id: "none", label: "Sin efecto", values: {} },

  { id: "slide60", label: "Diapositiva cálida años 60",
    values: { warmSlide: 75, rolloff: 45, grain: 25, vigOptical: 30, soft: 15, fade: 8 } },
  { id: "neg90", label: "Negativo frío años 90",
    values: { coolNeg: 70, grain: 35, fade: 18, rolloff: 35, vigOptical: 15 } },
  { id: "family70", label: "Álbum familiar años 70",
    values: { castYellow: 55, agedDesat: 45, fade: 40, rolloff: 50, grain: 40, soft: 25, vigOptical: 25, dust: 15 } },
  { id: "instant", label: "Instantánea desvaída",
    values: { fade: 50, split: 35, agedDesat: 35, rolloff: 60, instant: 60, soft: 30, vigOptical: 30, grain: 15 } },
  { id: "summer", label: "Verano quemado por el sol",
    values: { warmSlide: 50, leaks: 70, halation: 45, bloom: 30, fade: 25, grain: 30, vigOptical: 20 } },
  { id: "cross", label: "Proceso cruzado",
    values: { cross: 85, grain: 30, vigOptical: 35, lowRange: 25 } },
  { id: "expired", label: "Película caducada",
    values: { castMagenta: 55, fog: 35, fade: 35, grain: 60, agedDesat: 30, leaks: 20 } },
  { id: "xray", label: "Rayos X de aeropuerto",
    values: { fog: 75, castGreen: 25, grain: 45, agedDesat: 25, lowRange: 20 } },
  { id: "postcard", label: "Postal envejecida",
    values: { castYellow: 45, agedDesat: 60, fade: 35, paperBorder: 55, cracks: 35, stains: 25, soft: 20 } },
  { id: "cinema", label: "Cine nocturno",
    values: { halation: 70, split: 50, grain: 45, bloom: 35, lowRange: 20, vigOptical: 30 } },

  { id: "sepia1900", label: "Sepia de 1900",
    values: { sepia: 85, soft: 35, vigOptical: 55, fade: 20, dust: 35, scratches: 20, cracks: 20, grain: 25 } },
  { id: "cyanotype", label: "Cianotipia",
    values: { cyanotype: 90, soft: 25, paperBorder: 45, fade: 15, grain: 20 } },
  { id: "selenium", label: "Copia al selenio",
    values: { selenium: 85, rolloff: 30, grain: 30, vigOptical: 20 } },
  { id: "platinum", label: "Platino y paladio",
    values: { platinum: 90, fade: 20, rolloff: 45, soft: 20, paperBorder: 30 } },
  { id: "ortho1910", label: "Ortocromático de 1910",
    values: { panchro: 100, ortho: 95, lowRange: 30, soft: 40, vigOptical: 45, grain: 35, dust: 25 } },
  { id: "noir", label: "Noir de archivo",
    values: { panchro: 100, ortho: 60, lowRange: 45, grain: 55, scratches: 35, dust: 20, vigOptical: 40 } },
  { id: "daguerre", label: "Daguerrotipo desgastado",
    values: { platinum: 60, selenium: 25, vigMech: 55, soft: 55, cracks: 45, stains: 40, fog: 20 } },
  { id: "enlarger", label: "Copia de ampliadora",
    values: { panchro: 100, ortho: 40, paperBorder: 60, dust: 45, scratches: 25, grain: 30, rolloff: 25 } },
  { id: "scan35", label: "Negativo escaneado 35 mm",
    values: { filmBorder: 70, grain: 45, dust: 30, coolNeg: 30, fade: 15 } },

  { id: "toy", label: "Cámara de juguete",
    values: { vigMech: 60, soft: 40, ca: 50, leaks: 45, edgeBlur: 55, cross: 25, barrel: 30 } },
  { id: "petzval", label: "Objetivo de retrato antiguo",
    values: { swirl: 75, vigOptical: 45, edgeBlur: 35, soft: 20, warmSlide: 20 } },
  { id: "soviet", label: "Lente soviética",
    values: { swirl: 55, coma: 55, flare: 45, ca: 30, vigOptical: 30, bloom: 20 } },
  { id: "date98", label: "Compacta de 1998",
    values: { dateStamp: 90, warmSlide: 35, grain: 30, rolloff: 35, fade: 15, flare: 15 } },
  { id: "splitSoft", label: "Tonos partidos suaves",
    values: { split: 60, fade: 25, rolloff: 40, grain: 15 } },
  { id: "matte", label: "Mate contemporáneo",
    values: { fade: 55, agedDesat: 25, split: 20, grain: 20 } },
  { id: "nightShake", label: "Paseo nocturno a pulso",
    values: { shake: 55, halation: 45, bloom: 35, grain: 50, lowRange: 20 } },

  /* ── Décadas ── */
  { id: "d1920", cat: "Décadas", label: "Años 20: estudio de retrato",
    values: { sepia: 70, soft: 45, vigOptical: 60, fade: 15, dust: 30, cracks: 25, lowRange: 20, grain: 30 } },
  { id: "d1930", cat: "Décadas", label: "Años 30: noticiario",
    values: { panchro: 100, ortho: 70, lowRange: 35, grain: 60, scratches: 45, dust: 35, shake: 15, vigOptical: 35 } },
  { id: "d1940", cat: "Décadas", label: "Años 40: posguerra",
    values: { panchro: 100, ortho: 50, fade: 25, grain: 50, stains: 25, cracks: 20, soft: 30, vigOptical: 40, dust: 25 } },
  { id: "d1950", cat: "Décadas", label: "Años 50: primer color",
    values: { warmSlide: 45, agedDesat: 30, castYellow: 30, fade: 25, soft: 25, grain: 25, vigOptical: 25, rolloff: 40 } },
  { id: "d1950b", cat: "Décadas", label: "Años 50: anuncio de revista",
    values: { warmSlide: 55, castMagenta: 20, fade: 20, rolloff: 45, soft: 20, grain: 15 } },
  { id: "d1960b", cat: "Décadas", label: "Años 60: psicodelia",
    values: { cross: 55, warmSlide: 35, halation: 35, bloom: 30, grain: 30, vigOptical: 30, ca: 25 } },
  { id: "d1970b", cat: "Décadas", label: "Años 70: salón de casa",
    values: { castYellow: 65, fade: 35, agedDesat: 35, rolloff: 45, grain: 45, soft: 30, vigOptical: 20 } },
  { id: "d1970c", cat: "Décadas", label: "Años 70: verano en la costa",
    values: { warmSlide: 60, castYellow: 30, leaks: 35, fade: 30, grain: 35, rolloff: 55, bloom: 20 } },
  { id: "d1980", cat: "Décadas", label: "Años 80: flash directo",
    values: { coolNeg: 35, castMagenta: 25, lowRange: 30, grain: 30, vigOptical: 25, dateStamp: 40 } },
  { id: "d1980b", cat: "Décadas", label: "Años 80: neón y videoclub",
    values: { cross: 40, halation: 55, bloom: 40, split: 35, grain: 30, ca: 30 } },
  { id: "d1990b", cat: "Décadas", label: "Años 90: revelado de una hora",
    values: { coolNeg: 45, castGreen: 20, fade: 20, grain: 40, rolloff: 30, dateStamp: 55 } },
  { id: "d1990c", cat: "Décadas", label: "Años 90: desechable de fiesta",
    values: { coolNeg: 30, lowRange: 35, grain: 45, vigOptical: 35, flare: 20, soft: 20, dateStamp: 65 } },
  { id: "d2000", cat: "Décadas", label: "Años 2000: primera cámara digital",
    values: { coolNeg: 25, lowRange: 40, ca: 35, soft: 25, castGreen: 15, grain: 15 } },

  /* ── Películas en color ── */
  { id: "fReversalVivid", cat: "Películas en color", label: "Diapositiva saturada",
    values: { warmSlide: 85, lowRange: 20, rolloff: 25, grain: 15, vigOptical: 25 } },
  { id: "fReversalCool", cat: "Películas en color", label: "Diapositiva fría y limpia",
    values: { coolNeg: 55, lowRange: 15, rolloff: 25, grain: 12, vigOptical: 15 } },
  { id: "fPortrait", cat: "Películas en color", label: "Negativo de retrato suave",
    values: { warmSlide: 25, fade: 20, rolloff: 60, soft: 20, grain: 20, agedDesat: 15 } },
  { id: "fConsumer", cat: "Películas en color", label: "Negativo de consumo 200",
    values: { warmSlide: 35, castYellow: 20, grain: 35, rolloff: 40, fade: 12 } },
  { id: "fConsumerGreen", cat: "Películas en color", label: "Negativo verdoso 400",
    values: { coolNeg: 45, castGreen: 35, grain: 45, fade: 20, rolloff: 35 } },
  { id: "fTungsten", cat: "Películas en color", label: "Película de tungsteno de noche",
    values: { coolNeg: 70, halation: 55, bloom: 30, grain: 50, lowRange: 20 } },
  { id: "fCinemaNeg", cat: "Películas en color", label: "Negativo de cine",
    values: { split: 45, halation: 35, fade: 20, rolloff: 50, grain: 35 } },
  { id: "fBleach", cat: "Películas en color", label: "Blanqueo parcial (sin blanqueo)",
    values: { agedDesat: 60, lowRange: 45, grain: 45, coolNeg: 20, vigOptical: 25 } },
  { id: "fRedscale", cat: "Películas en color", label: "Película invertida (redscale)",
    values: { warmSlide: 90, castMagenta: 45, castYellow: 40, grain: 40, fade: 20, vigOptical: 30 } },
  { id: "fAerochrome", cat: "Películas en color", label: "Infrarrojo en falso color",
    values: { cross: 70, castMagenta: 60, halation: 30, grain: 30 } },
  { id: "fPushed", cat: "Películas en color", label: "Forzada dos pasos",
    values: { lowRange: 50, grain: 75, coolNeg: 25, vigOptical: 20, halation: 20 } },
  { id: "fPulled", cat: "Películas en color", label: "Subrevelada y lechosa",
    values: { fade: 55, agedDesat: 30, rolloff: 45, grain: 25, soft: 15 } },

  /* ── Blanco y negro ── */
  { id: "bwClassic", cat: "Blanco y negro", label: "Blanco y negro clásico",
    values: { panchro: 100, ortho: 30, grain: 35, rolloff: 25, vigOptical: 20 } },
  { id: "bwHighContrast", cat: "Blanco y negro", label: "Alto contraste de calle",
    values: { panchro: 100, ortho: 45, lowRange: 55, grain: 60, vigOptical: 25 } },
  { id: "bwSoft", cat: "Blanco y negro", label: "Gris suave de galería",
    values: { panchro: 100, platinum: 55, fade: 25, rolloff: 45, soft: 20, grain: 15 } },
  { id: "bwReportage", cat: "Blanco y negro", label: "Reportaje de guerra",
    values: { panchro: 100, ortho: 55, lowRange: 40, grain: 75, scratches: 30, dust: 25, shake: 15, vigOptical: 35 } },
  { id: "bwInfrared", cat: "Blanco y negro", label: "Infrarrojo en blanco y negro",
    values: { panchro: 100, ortho: 40, halation: 55, bloom: 50, grain: 45, fog: 15 } },
  { id: "bwNewsprint", cat: "Blanco y negro", label: "Foto de periódico",
    values: { panchro: 100, ortho: 50, lowRange: 45, fade: 30, grain: 70, soft: 25, stains: 15 } },
  { id: "bwFilmNoir", cat: "Blanco y negro", label: "Cine negro",
    values: { panchro: 100, ortho: 55, lowRange: 55, halation: 25, grain: 45, vigOptical: 55 } },
  { id: "bwContact", cat: "Blanco y negro", label: "Hoja de contactos",
    values: { panchro: 100, ortho: 35, filmBorder: 80, grain: 40, dust: 20 } },
  { id: "bwLith", cat: "Blanco y negro", label: "Copia lith",
    values: { panchro: 100, sepia: 45, lowRange: 40, grain: 65, fade: 15, vigOptical: 30 } },

  /* ── Procesos antiguos ── */
  { id: "pAlbumen", cat: "Procesos antiguos", label: "Albúmina del siglo XIX",
    values: { sepia: 65, castMagenta: 20, fade: 20, soft: 40, cracks: 35, stains: 30, vigOptical: 45 } },
  { id: "pTintype", cat: "Procesos antiguos", label: "Ferrotipo",
    values: { panchro: 100, platinum: 50, lowRange: 40, vigMech: 45, soft: 45, scratches: 25, stains: 35, ortho: 50 } },
  { id: "pAmbrotype", cat: "Procesos antiguos", label: "Ambrotipo",
    values: { selenium: 50, fog: 25, soft: 40, vigOptical: 55, cracks: 30, dust: 25 } },
  { id: "pGumPrint", cat: "Procesos antiguos", label: "Goma bicromatada",
    values: { sepia: 40, fade: 35, soft: 60, paperBorder: 50, stains: 25, grain: 30 } },
  { id: "pSaltPrint", cat: "Procesos antiguos", label: "Papel a la sal",
    values: { sepia: 55, castYellow: 20, fade: 40, soft: 45, paperBorder: 40, vigOptical: 35 } },
  { id: "pCyanFaded", cat: "Procesos antiguos", label: "Cianotipia desvaída",
    values: { cyanotype: 65, fade: 40, paperBorder: 55, stains: 20, soft: 20 } },
  { id: "pAutochrome", cat: "Procesos antiguos", label: "Autocromo de 1910",
    values: { agedDesat: 35, warmSlide: 25, grain: 80, soft: 40, vigOptical: 45, castGreen: 15 } },
  { id: "pHandColored", cat: "Procesos antiguos", label: "Coloreada a mano",
    values: { sepia: 30, agedDesat: 45, warmSlide: 30, fade: 25, soft: 30, paperBorder: 35 } },
  { id: "pGlassPlate", cat: "Procesos antiguos", label: "Placa de vidrio",
    values: { panchro: 100, ortho: 70, soft: 35, vigOptical: 50, cracks: 40, dust: 40, stains: 20, fog: 15 } },

  /* ── Cámaras y ópticas ── */
  { id: "cBox", cat: "Cámaras y ópticas", label: "Cámara de cajón",
    values: { vigMech: 50, soft: 50, edgeBlur: 45, barrel: 20, sepia: 25, grain: 30 } },
  { id: "cTLR", cat: "Cámaras y ópticas", label: "Formato medio bireflex",
    values: { vigOptical: 30, rolloff: 45, grain: 25, warmSlide: 20, filmBorder: 25 } },
  { id: "cHalfFrame", cat: "Cámaras y ópticas", label: "Medio formato de bolsillo",
    values: { grain: 55, soft: 25, vigOptical: 35, warmSlide: 25, leaks: 25 } },
  { id: "cPinhole", cat: "Cámaras y ópticas", label: "Estenopeica",
    values: { soft: 70, vigOptical: 70, edgeBlur: 40, grain: 35, fade: 15 } },
  { id: "cPlasticLens", cat: "Cámaras y ópticas", label: "Lente de plástico",
    values: { soft: 45, ca: 60, bloom: 40, vigOptical: 45, leaks: 30 } },
  { id: "cFisheye", cat: "Cámaras y ópticas", label: "Ojo de pez de juguete",
    values: { barrel: 85, vigMech: 55, ca: 35, soft: 20, cross: 25 } },
  { id: "cTiltShift", cat: "Cámaras y ópticas", label: "Miniatura (desenfoque de bordes)",
    values: { edgeBlur: 80, warmSlide: 30, lowRange: 20 } },
  { id: "cSoftFocus", cat: "Cámaras y ópticas", label: "Filtro de difusión de estudio",
    values: { bloom: 60, soft: 35, rolloff: 50, halation: 25, fade: 10 } },
  { id: "cUncoated", cat: "Cámaras y ópticas", label: "Lente sin tratamiento a contraluz",
    values: { flare: 70, bloom: 55, fog: 25, halation: 30 } },
  { id: "cSuper8", cat: "Cámaras y ópticas", label: "Fotograma de súper 8",
    values: { warmSlide: 45, grain: 70, soft: 35, vigMech: 35, scratches: 30, dust: 30, shake: 20 } },
  { id: "cVHS", cat: "Cámaras y ópticas", label: "Captura de cinta de vídeo",
    values: { ca: 55, soft: 45, lowRange: 30, coolNeg: 25, grain: 30, shake: 15, dateStamp: 40 } },

  /* ── Creativos ── */
  { id: "xDreamy", cat: "Creativos", label: "Soñadora",
    values: { bloom: 60, fade: 35, split: 30, soft: 30, leaks: 25, rolloff: 50 } },
  { id: "xMoody", cat: "Creativos", label: "Melancólica",
    values: { coolNeg: 40, agedDesat: 40, fade: 30, lowRange: 20, vigOptical: 40, grain: 30 } },
  { id: "xGolden", cat: "Creativos", label: "Hora dorada",
    values: { warmSlide: 70, leaks: 40, halation: 30, bloom: 30, rolloff: 45, grain: 20 } },
  { id: "xBurntFilm", cat: "Creativos", label: "Película quemada",
    values: { leaks: 90, halation: 45, fade: 25, grain: 45, scratches: 25, filmBorder: 35 } },
  { id: "xDamaged", cat: "Creativos", label: "Archivo muy dañado",
    values: { agedDesat: 50, fade: 40, dust: 70, scratches: 60, stains: 55, cracks: 55, grain: 50 } },
  { id: "xFoundPhoto", cat: "Creativos", label: "Foto encontrada en un mercadillo",
    values: { castYellow: 50, agedDesat: 50, fade: 45, paperBorder: 60, stains: 35, cracks: 30, instant: 20 } },
  { id: "xPolaroidCool", cat: "Creativos", label: "Instantánea fría",
    values: { coolNeg: 45, fade: 40, instant: 55, soft: 25, vigOptical: 25, rolloff: 50 } },
  { id: "xPolaroidWarm", cat: "Creativos", label: "Instantánea cálida",
    values: { warmSlide: 50, fade: 35, instant: 60, soft: 25, vigOptical: 25, rolloff: 55 } },
  { id: "xGhost", cat: "Creativos", label: "Fantasmagórica",
    values: { shake: 70, fog: 35, agedDesat: 50, bloom: 30, vigOptical: 45 } },
  { id: "xKodachromeLike", cat: "Creativos", label: "Postal de viaje saturada",
    values: { warmSlide: 70, lowRange: 25, vigOptical: 30, paperBorder: 30, grain: 15 } },
  { id: "xNightClub", cat: "Creativos", label: "Discoteca con flash",
    values: { cross: 45, halation: 50, lowRange: 35, grain: 40, ca: 25, vigOptical: 30 } },
  { id: "xRainyCity", cat: "Creativos", label: "Ciudad lluviosa",
    values: { coolNeg: 55, halation: 40, bloom: 30, fade: 20, grain: 35, split: 25 } },

  /* ── Estaciones y ambientes ── */
  { id: "sAutumn", cat: "Estaciones y ambientes", label: "Otoño",
    values: { warmSlide: 55, castYellow: 30, agedDesat: 15, fade: 20, grain: 25, vigOptical: 25 } },
  { id: "sWinter", cat: "Estaciones y ambientes", label: "Invierno",
    values: { coolNeg: 60, agedDesat: 25, fade: 25, rolloff: 45, grain: 20 } },
  { id: "sSpring", cat: "Estaciones y ambientes", label: "Primavera",
    values: { split: 35, fade: 25, bloom: 30, rolloff: 45, soft: 15 } },
  { id: "sBeach", cat: "Estaciones y ambientes", label: "Playa al mediodía",
    values: { warmSlide: 45, fade: 30, rolloff: 60, bloom: 25, grain: 20 } },
  { id: "sForest", cat: "Estaciones y ambientes", label: "Bosque húmedo",
    values: { coolNeg: 35, castGreen: 40, fade: 20, soft: 20, vigOptical: 35, grain: 25 } },
  { id: "sDesert", cat: "Estaciones y ambientes", label: "Desierto polvoriento",
    values: { castYellow: 55, fog: 30, fade: 30, grain: 40, dust: 35 } },
  { id: "sMountain", cat: "Estaciones y ambientes", label: "Montaña de postal",
    values: { coolNeg: 30, lowRange: 20, vigOptical: 30, paperBorder: 40, grain: 20 } },
  { id: "sCandle", cat: "Estaciones y ambientes", label: "Luz de velas",
    values: { warmSlide: 75, halation: 45, bloom: 35, grain: 45, vigOptical: 40, lowRange: 20 } },
  { id: "sFog", cat: "Estaciones y ambientes", label: "Niebla matinal",
    values: { fog: 55, fade: 30, agedDesat: 30, soft: 25, rolloff: 40 } }
];

/* Categoría de cada estilo para agruparlos en el desplegable. Los
   originales no la declaran: van a «Clásicos» (salvo los procesos B/N
   y de ópticas, que se reparten en sus grupos). */
const ORIGINAL_CATS = { sepia1900: "Procesos antiguos", cyanotype: "Procesos antiguos", selenium: "Procesos antiguos",
  platinum: "Procesos antiguos", daguerre: "Procesos antiguos", ortho1910: "Blanco y negro", noir: "Blanco y negro",
  enlarger: "Blanco y negro", toy: "Cámaras y ópticas", petzval: "Cámaras y ópticas", soviet: "Cámaras y ópticas",
  date98: "Décadas", slide60: "Décadas", neg90: "Décadas", family70: "Décadas", scan35: "Películas en color",
  cross: "Películas en color", expired: "Películas en color", xray: "Películas en color" };
for(const p of PRESETS) if(!p.cat) p.cat = p.id === "none" ? "" : ORIGINAL_CATS[p.id] || "Clásicos";
export const PRESET_CATS = ["Clásicos", "Décadas", "Películas en color", "Blanco y negro", "Procesos antiguos", "Cámaras y ópticas", "Creativos", "Estaciones y ambientes"];

export const preset = id => PRESETS.find(p => p.id === id);
